/* Hex Lab is deliberately isolated from the square campaign simulation. */
(function(root){
  const directions=[['E',1,0],['NE',1,-1],['NW',0,-1],['W',-1,0],['SW',-1,1],['SE',0,1]];
  const byName=Object.fromEntries(directions.map(item=>[item[0],item]));
  const key=(q,r)=>`${q},${r}`;
  const clone=value=>JSON.parse(JSON.stringify(value));
  const neighbor=(q,r,dir)=>{const d=typeof dir==='string'?byName[dir]:dir;return[q+d[1],r+d[2]];};
  const neighbors=(q,r)=>directions.map(d=>({direction:d[0],q:q+d[1],r:r+d[2]}));
  const cellAt=(state,q,r)=>state.cells[key(q,r)]||null;
  const isBurnable=cell=>!!cell&&['tree','wheat','farmstead'].includes(cell.object)&&cell.fire==='normal';
  function makeCells(rows,features){const cells={};for(let r=0;r<rows;r++)for(let q=0;q<rows;q++)cells[key(q,r)]={q,r,object:null,fire:'normal'};for(const [q,r,object,fire='normal'] of features)if(cells[key(q,r)]){cells[key(q,r)].object=object;cells[key(q,r)].fire=fire;}return cells;}
  const definitions={
    a:{id:'hex-a-cut-the-line',title:'Test A — Cut the Line',subtitle:'Make a precise cut before Fire claims the grove.',moves:2,req:{wood:4,charcoal:3},tools:['woodcutter','wait'],cells:makeCells(5,[
      [0,2,'tree','active'],[1,2,'tree'],[2,2,'tree'],[3,2,'tree'],[4,2,'tree'],[1,1,'tree'],[1,3,'tree'],[2,1,'tree'],[2,3,'tree'],[3,1,'tree'],[3,3,'tree'],[4,1,'tree'],[4,3,'tree']
    ])},
    b:{id:'hex-b-six-sides',title:'Test B — Six Sides',subtitle:'Choose the firebreak that keeps the Farmstead safe.',moves:2,req:{wood:3,charcoal:3},tools:['woodcutter','wait'],cells:makeCells(5,[
      [0,2,'tree','active'],[1,2,'tree'],[2,2,'tree'],[3,2,'tree'],[4,2,'farmstead'],[1,1,'tree'],[2,1,'tree'],[3,1,'tree'],[1,3,'tree'],[2,3,'tree'],[3,3,'tree'],[4,1,'tree'],[4,3,'tree']
    ])},
    c:{id:'hex-c-iron-grove',title:'Test C — Iron Grove',subtitle:'Trees must serve Wood, Iron, Charcoal and the firebreak.',moves:3,req:{iron:3,wood:3,charcoal:2},tools:['forge','woodcutter','wait'],cells:makeCells(6,[
      [0,3,'tree','active'],[1,3,'tree'],[2,3,'tree'],[3,3,'tree'],[4,3,'tree'],[5,3,'tree'],[1,2,'tree'],[2,2,'tree'],[3,2,'tree'],[4,2,'tree'],[2,4,'tree'],[3,4,'tree'],[4,4,'tree'],[4,1,'ore'],[5,1,'ore'],[4,0,'ore'],[5,0,'ore'],[5,2,'farmstead']
    ])}
  };
  function createInitialState(definition){return{definitionId:definition.id,moves:definition.moves,worldSteps:0,res:{wood:0,wheat:0,charcoal:0,iron:0},cells:clone(definition.cells),lost:false,won:false};}
  function connected(state,q,r,object){const start=cellAt(state,q,r);if(!start||start.object!==object)return[];const seen=new Set([key(q,r)]),out=[];for(let i=0;i<out.length+1;i++){const current=i?out[i-1]:start;if(i===0)out.push(start);for(const next of neighbors(current.q,current.r)){const cell=cellAt(state,next.q,next.r);if(cell&&cell.object===object&&!seen.has(key(cell.q,cell.r))){seen.add(key(cell.q,cell.r));out.push(cell);}}}return out;}
  function cutLine(state,q,r,direction){const out=[],start=cellAt(state,q,r);if(!start||start.object!=='tree')return out;let cq=q,cr=r;for(let i=0;i<3;i++){const cell=cellAt(state,cq,cr);if(!cell||cell.object!=='tree'||cell.fire!=='normal')break;out.push(cell);[cq,cr]=neighbor(cq,cr,direction);}return out;}
  function forgePlan(state,q,r){const center=cellAt(state,q,r);if(!center||center.fire!=='normal'||['ore','farmstead','forge'].includes(center.object))return null;const around=neighbors(q,r).map(n=>cellAt(state,n.q,n.r)).filter(Boolean),fuel=around.filter(cell=>cell.object==='tree'&&cell.fire==='normal').sort((a,b)=>a.r-b.r||a.q-b.q),oreStarts=around.filter(cell=>cell.object==='ore').sort((a,b)=>a.r-b.r||a.q-b.q),seen=new Set(),ore=[];for(const start of oreStarts)for(const cell of connected(state,start.q,start.r,'ore'))if(!seen.has(key(cell.q,cell.r))){seen.add(key(cell.q,cell.r));ore.push(cell);}ore.sort((a,b)=>a.r-b.r||a.q-b.q);const count=Math.min(fuel.length,ore.length);return{center,fuel:fuel.slice(0,count),ore:ore.slice(0,count),count};}
  function getLegalActions(definition,state){if(state.lost||state.won)return[];const actions=[];for(const cell of Object.values(state.cells)){
      if(definition.tools.includes('woodcutter')&&cell.object==='tree'&&cell.fire==='normal')for(const [direction] of directions)if(cutLine(state,cell.q,cell.r,direction).length)actions.push({tool:'woodcutter',q:cell.q,r:cell.r,direction});
      if(definition.tools.includes('sickle')&&cell.object==='wheat'&&cell.fire==='normal')actions.push({tool:'sickle',q:cell.q,r:cell.r});
      if(definition.tools.includes('forge')&&forgePlan(state,cell.q,cell.r)?.count)actions.push({tool:'forge',q:cell.q,r:cell.r});
    }
    if(definition.tools.includes('wait'))actions.push({tool:'wait'});return actions;
  }
  function resolveFire(state){const active=Object.values(state.cells).filter(cell=>cell.fire==='active'),dying=Object.values(state.cells).filter(cell=>cell.fire==='dying'),ignitions=[];for(const source of active)for(const next of neighbors(source.q,source.r)){const target=cellAt(state,next.q,next.r);if(isBurnable(target))ignitions.push(target);}const unique=new Map(ignitions.map(cell=>[key(cell.q,cell.r),cell]));for(const cell of active)cell.fire='dying';for(const cell of dying){cell.fire='burnt';if(cell.object==='tree')state.res.charcoal++;cell.object=null;}for(const cell of unique.values()){if(cell.object==='farmstead')state.lost=true;cell.fire='active';if(cell.object==='wheat')cell.object=null;}}
  function updateStatus(definition,state){state.won=!state.lost&&Object.entries(definition.req).every(([resource,amount])=>(state.res[resource]||0)>=amount);return state;}
  function applyAction(definition,input,action){const state=clone(input);if(state.lost||state.won)throw new Error('The Hex Lab state is finished.');const legal=getLegalActions(definition,state),signature=item=>`${item.tool}:${item.q??''}:${item.r??''}:${item.direction??''}`;if(!legal.some(item=>signature(item)===signature(action)))throw new Error('Illegal Hex Lab action.');let log='';if(action.tool==='woodcutter'){const trees=cutLine(state,action.q,action.r,action.direction);for(const tree of trees)tree.object=null;state.res.wood+=trees.length;state.moves--;log=`WOODCUTTER · start q${action.q}, r${action.r} · ${action.direction} · Trees harvested: ${trees.length}`;}
    if(action.tool==='sickle'){const wheat=connected(state,action.q,action.r,'wheat');for(const cell of wheat)cell.object=null;state.res.wheat+=wheat.length;state.moves--;log=`SICKLE · Wheat harvested: ${wheat.length}`;}
    if(action.tool==='forge'){const plan=forgePlan(state,action.q,action.r);plan.center.object='forge';for(const fuel of plan.fuel)fuel.object=null;for(const ore of plan.ore)ore.object=null;state.res.iron+=plan.count;state.moves--;log=`FORGE · q${action.q}, r${action.r} · Fuel: ${plan.fuel.length} · Ore: ${plan.ore.length} · Iron +${plan.count}`;}
    if(action.tool==='wait')log='WAIT';resolveFire(state);state.worldSteps++;updateStatus(definition,state);return{state,log};}
  function counts(definition,state){const actions=getLegalActions(definition,state),out={woodcutter:0,forge:0,sickle:0,wait:false,total:actions.length};for(const action of actions){if(action.tool==='wait')out.wait=true;else out[action.tool]++;}return out;}
  function token(cell){if(cell.fire==='active')return '🔥';if(cell.fire==='dying')return '♨';if(cell.fire==='burnt')return '●';return({tree:'♣',wheat:'✦',ore:'◆',farmstead:'⌂',forge:'⚒'}[cell.object]||'');}
  function mount(){if(!root.document||document.querySelector('#hexLabScreen'))return;const screen=document.createElement('section');screen.id='hexLabScreen';screen.className='screen';screen.setAttribute('aria-label','Hex Lab developer experiment');screen.innerHTML='<main class="hex-lab"><div class="hex-lab-head"><p class="eyebrow">Developer gameplay experiment</p><h1>Hex Lab</h1><p>Pointy-top axial hexes · six shared-edge neighbours · isolated from campaign.</p></div><div class="hex-lab-tests" id="hexLabTests"></div><div class="hex-lab-info"><strong id="hexLabTitle"></strong><span id="hexLabHint"></span></div><div id="hexLabResources" class="hex-lab-resources"></div><div id="hexLabBoard" class="hex-board" aria-label="Hex Lab board"></div><div class="hex-lab-tools"><button data-hex-tool="woodcutter">Woodcutter<br><small>Cut up to 3 Trees</small></button><button data-hex-tool="sickle">Sickle<br><small>Whole Wheat region</small></button><button data-hex-tool="forge">Forge<br><small>Six adjacent hexes</small></button><button id="hexLabWait">Wait<br><small>0 moves · world step</small></button></div><div id="hexLabDirections" class="hex-directions" hidden></div><div class="hex-lab-actions"><button id="hexLabUndo">Undo</button><button id="hexLabRestart">Restart</button><button id="hexLabBack">Back to game</button></div><details class="hex-lab-debug" open><summary>Action-space debug</summary><p id="hexLabActions"></p><p id="hexLabPreview">Choose a tool, then a hex.</p><ol id="hexLabHistory"></ol></details></main>';document.body.append(screen);
    const style=document.createElement('style');style.textContent='.hex-lab{max-width:620px;margin:auto;padding:18px 12px 44px;color:#373b32}.hex-lab h1{margin:0;font-size:1.7rem}.hex-lab-head p{margin:.35rem 0;color:#6f675b}.hex-lab-tests,.hex-lab-tools,.hex-lab-actions,.hex-directions{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.hex-lab button{font:inherit;border:1px solid #bcad91;border-radius:10px;padding:9px 10px;background:#fff9ed;color:#3b4034}.hex-lab button.selected{background:#dce8c8;border-color:#758956}.hex-lab button:disabled{opacity:.38}.hex-lab button small{font-size:.68rem;color:#6d6a5c}.hex-lab-info{display:grid;gap:2px;padding:9px 11px;background:#f4eddc;border:1px solid #ddcfb8;border-radius:10px}.hex-lab-info span{font-size:.82rem;color:#70695d}.hex-lab-resources{display:flex;gap:6px;flex-wrap:wrap;margin:9px 0}.hex-lab-resources span{padding:5px 7px;border-radius:7px;background:#f5efe2;border:1px solid #d8c9af;font-size:.75rem;font-weight:700}.hex-board{position:relative;margin:8px auto 12px;background:#d7c49f;border:6px solid #9a7045;border-radius:18px;box-shadow:inset 0 0 0 2px #c69e6d;touch-action:none;overflow:hidden}.hex-tile{position:absolute;display:grid;place-items:center;clip-path:polygon(50% 0,93.3% 25%,93.3% 75%,50% 100%,6.7% 75%,6.7% 25%);background:#91a67b;color:#34442f;font-size:1.35rem;filter:drop-shadow(0 1px 0 #62785755);padding-top:1px}.hex-tile.ore{background:#9ca29a}.hex-tile.farmstead{background:#b6a77b}.hex-tile.forge{background:#92978d}.hex-tile.active{background:#d16b38;color:#fff2b6}.hex-tile.dying{background:#855944;color:#f1c68d}.hex-tile.burnt{background:#514f45;color:#817b68}.hex-tile.preview{outline:3px solid #f4c85b;outline-offset:-5px;filter:brightness(1.13)}.hex-lab-debug{padding:10px;background:#f5efe2;border:1px solid #ded0ba;border-radius:10px;font-size:.82rem}.hex-lab-debug p{margin:6px 0}.hex-lab-debug ol{margin:7px 0;padding-left:20px}.hex-directions button{min-width:48px}.hex-status{font-weight:800;color:#9c4c32}';document.head.append(style);
    const tests=root.document.querySelector('#hexLabTests'),board=root.document.querySelector('#hexLabBoard'),directionsEl=root.document.querySelector('#hexLabDirections');let definition=definitions.a,state=createInitialState(definition),history=[],tool=null,pending=null,preview=[],dragDirection=null;
    function setDefinition(id){definition=definitions[id];state=createInitialState(definition);history=[];tool=null;pending=null;preview=[];render();}
    function directionFromPointer(event,cell){const rect=board.getBoundingClientRect(),center={x:parseFloat(event.currentTarget.style.left)+parseFloat(event.currentTarget.style.width)/2+rect.left,y:parseFloat(event.currentTarget.style.top)+parseFloat(event.currentTarget.style.height)/2+rect.top};const dx=event.clientX-center.x,dy=event.clientY-center.y;let best=null;for(const [name,dq,dr] of directions){const vx=Math.sqrt(3)*(dq+dr/2),vy=1.5*dr,score=(dx*vx+dy*vy)/Math.sqrt(vx*vx+vy*vy);if(!best||score>best.score)best={name,score};}return best?.name;}
    function render(){tests.innerHTML=Object.values(definitions).map(def=>`<button data-hex-test="${def.id}" class="${def.id===definition.id?'selected':''}">${def.title.replace('Test ','')}</button>`).join('');tests.querySelectorAll('[data-hex-test]').forEach(button=>button.onclick=()=>setDefinition(button.dataset.hexTest));root.document.querySelector('#hexLabTitle').textContent=definition.title;root.document.querySelector('#hexLabHint').textContent=definition.subtitle;root.document.querySelector('#hexLabResources').innerHTML=`<span>Moves ${state.moves}</span>${Object.entries(definition.req).map(([name,need])=>`<span>${name} ${state.res[name]||0}/${need}</span>`).join('')}<span>World steps ${state.worldSteps}</span>${state.lost?'<span class="hex-status">Farmstead lost</span>':state.won?'<span class="hex-status">Land secured</span>':''}`;
      const cells=Object.values(state.cells),size=39,xs=cells.map(c=>Math.sqrt(3)*size*(c.q+c.r/2)),ys=cells.map(c=>1.5*size*c.r),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),w=maxX-minX+Math.sqrt(3)*size+14,h=maxY-minY+2*size+14;board.style.width=`${w}px`;board.style.height=`${h}px`;board.innerHTML=cells.map(cell=>{const x=Math.sqrt(3)*size*(cell.q+cell.r/2)-minX+7,y=1.5*size*cell.r-minY+7,classes=['hex-tile',cell.object||'',cell.fire==='active'?'active':'',cell.fire==='dying'?'dying':'',cell.fire==='burnt'?'burnt':'',preview.some(item=>item.q===cell.q&&item.r===cell.r)?'preview':''].filter(Boolean).join(' ');return`<button class="${classes}" data-q="${cell.q}" data-r="${cell.r}" style="left:${x}px;top:${y}px;width:${Math.sqrt(3)*size}px;height:${2*size}px" aria-label="q ${cell.q} r ${cell.r} ${cell.object||'ground'}">${token(cell)}</button>`;}).join('');board.querySelectorAll('.hex-tile').forEach(button=>{const q=+button.dataset.q,r=+button.dataset.r;button.onpointerdown=event=>{if(tool!=='woodcutter')return;const cell=cellAt(state,q,r);if(cell?.object!=='tree')return;pending={q,r};preview=[cell];render();};button.onpointermove=event=>{if(tool!=='woodcutter'||!pending)return;const direction=directionFromPointer(event,cellAt(state,pending.q,pending.r));if(direction&&direction!==dragDirection){dragDirection=direction;preview=cutLine(state,pending.q,pending.r,direction);render();}};button.onpointerup=()=>{if(tool==='woodcutter'&&pending&&dragDirection&&preview.length){commit({tool:'woodcutter',q:pending.q,r:pending.r,direction:dragDirection});}};button.onclick=()=>choose(q,r);});
      const allDirections=pending?directions.map(([name])=>`<button data-hex-dir="${name}" class="${dragDirection===name?'selected':''}">${name}</button>`).join(''):'';directionsEl.hidden=!pending;directionsEl.innerHTML=allDirections;directionsEl.querySelectorAll('[data-hex-dir]').forEach(button=>button.onclick=()=>{const direction=button.dataset.hexDir;preview=cutLine(state,pending.q,pending.r,direction);dragDirection=direction;render();commit({tool:'woodcutter',q:pending.q,r:pending.r,direction});});
      root.document.querySelectorAll('[data-hex-tool]').forEach(button=>{const available=definition.tools.includes(button.dataset.hexTool);button.hidden=!available;button.classList.toggle('selected',tool===button.dataset.hexTool);button.onclick=()=>{tool=tool===button.dataset.hexTool?null:button.dataset.hexTool;pending=null;preview=[];render();};});const c=counts(definition,state);root.document.querySelector('#hexLabActions').textContent=`LEGAL ACTIONS · Woodcutter: ${c.woodcutter} · Forge: ${c.forge} · Sickle: ${c.sickle} · Wait: ${c.wait?'yes':'no'} · TOTAL: ${c.total}`;root.document.querySelector('#hexLabPreview').textContent=pending?`Woodcutter start q${pending.q}, r${pending.r}. Drag or choose one of six directions; preview highlights ${preview.length} Tree${preview.length===1?'':'s'}.`:'Choose a tool, then a hex.';root.document.querySelector('#hexLabHistory').innerHTML=history.map(item=>`<li>${item}</li>`).join('');root.document.querySelector('#hexLabUndo').disabled=!history.length;}
    function choose(q,r){if(!tool)return;if(tool==='woodcutter'){const cell=cellAt(state,q,r);if(cell?.object==='tree'){pending={q,r};preview=[cell];dragDirection=null;render();}return;}if(tool==='sickle')commit({tool,q,r});if(tool==='forge')commit({tool,q,r});}
    function commit(action){try{history.push({state:clone(state),log:null});const result=applyAction(definition,state,action);state=result.state;history.at(-1).log=result.log;history=history.slice(-30);tool=null;pending=null;preview=[];dragDirection=null;render();}catch(error){root.document.querySelector('#hexLabPreview').textContent=error.message;}}
    root.document.querySelector('#hexLabWait').onclick=()=>commit({tool:'wait'});root.document.querySelector('#hexLabUndo').onclick=()=>{const prior=history.pop();if(prior)state=prior.state;tool=null;pending=null;preview=[];render();};root.document.querySelector('#hexLabRestart').onclick=()=>setDefinition(definition.id);root.document.querySelector('#hexLabBack').onclick=()=>root.SootSeedGame.showMenu();const controls=root.document.querySelector('.campaign-debug');if(controls){const button=document.createElement('button');button.type='button';button.textContent='Hex Lab';button.onclick=()=>{setDefinition('a');root.SootSeedGame.showScreen('hexLabScreen');};controls.append(button);}render();}
  root.SootSeedHexLab={directions,definitions,key,neighbor,neighbors,createInitialState,connected,cutLine,forgePlan,getLegalActions,resolveFire,applyAction,counts,mount};
  if(root.document)mount();
})(globalThis);
