/* Production hex core and developer sandbox. It does not consume square-game state. */
(function(root){
  const SQRT3=Math.sqrt(3),directions=[['E',1,0],['NE',1,-1],['NW',0,-1],['W',-1,0],['SW',-1,1],['SE',0,1]],byName=Object.fromEntries(directions.map(x=>[x[0],x])),key=(q,r)=>`${q},${r}`,clone=x=>JSON.parse(JSON.stringify(x));
  /* Flat-top axial projection. G is an actual perpendicular edge gap, not a margin. */
  const neighbor=(q,r,d)=>{const x=typeof d==='string'?byName[d]:d;return[q+x[1],r+x[2]]},neighbors=(q,r)=>directions.map(([direction,dq,dr])=>({direction,q:q+dq,r:r+dr})),geometry=(radius,gap=0)=>{const distance=SQRT3*radius+gap;return{radius,gap,width:2*radius,height:SQRT3*radius,distance,horizontal:1.5*radius,vertical:distance,ratio:2/SQRT3}},point=(q,r,radius,gap=0)=>{const distance=SQRT3*radius+gap;return{x:SQRT3/2*distance*q,y:distance*(r+q/2)}},at=(state,q,r)=>state.cells[key(q,r)]||null;
  const normalTree=c=>!!c&&c.terrain==='ground'&&c.object==='tree'&&c.fire==='normal',burnable=c=>!!c&&c.terrain==='ground'&&['tree','wheat','farmstead'].includes(c.object)&&c.fire==='normal';
  function makeCells(side,features){const cells={};for(let r=0;r<side;r++)for(let q=0;q<side;q++)cells[key(q,r)]={q,r,terrain:'ground',object:null,fire:'normal'};for(const [q,r,object,fire='normal'] of features)if(cells[key(q,r)])Object.assign(cells[key(q,r)],{object,fire});return cells}
  const definitions={
    a:{id:'hex-a-cut-the-line',title:'Test A — Cut the Line',subtitle:'Make a precise cut before Fire claims the grove.',moves:2,req:{wood:4,charcoal:3},tools:['woodcutter','wait'],cells:makeCells(5,[[0,2,'tree','active'],[1,2,'tree'],[2,2,'tree'],[3,2,'tree'],[4,2,'tree'],[1,1,'tree'],[1,3,'tree'],[2,1,'tree'],[2,3,'tree'],[3,1,'tree'],[3,3,'tree'],[4,1,'tree'],[4,3,'tree']])},
    b:{id:'hex-b-six-sides',title:'Test B — Six Sides',subtitle:'Choose the firebreak that keeps the Farmstead safe.',moves:2,req:{wood:3,charcoal:3},tools:['woodcutter','wait'],cells:makeCells(5,[[0,2,'tree','active'],[1,2,'tree'],[2,2,'tree'],[3,2,'tree'],[4,2,'farmstead'],[1,1,'tree'],[2,1,'tree'],[3,1,'tree'],[1,3,'tree'],[2,3,'tree'],[3,3,'tree'],[4,1,'tree'],[4,3,'tree']])},
    c:{id:'hex-c-iron-grove',title:'Test C — Iron Grove',subtitle:'Trees must serve Wood, Iron, Charcoal and the firebreak.',moves:3,req:{iron:3,wood:3,charcoal:2},tools:['forge','woodcutter','wait'],cells:makeCells(6,[[0,3,'tree','active'],[1,3,'tree'],[2,3,'tree'],[3,3,'tree'],[4,3,'tree'],[5,3,'tree'],[1,2,'tree'],[2,2,'tree'],[3,2,'tree'],[4,2,'tree'],[2,4,'tree'],[3,4,'tree'],[4,4,'tree'],[4,1,'ore'],[5,1,'ore'],[4,0,'ore'],[5,0,'ore'],[5,2,'farmstead']])}
  };
  function validateDefinition(def){const errors=[],seen=new Set();if(!def?.id)errors.push('Level needs an id.');if(!Number.isInteger(def?.moves)||def.moves<0)errors.push('Moves must be a non-negative integer.');if(!Array.isArray(def?.tools))errors.push('Tools must be an array.');for(const c of Object.values(def?.cells||{})){if(!Number.isInteger(c.q)||!Number.isInteger(c.r))errors.push('Every hex needs integer q and r coordinates.');if(seen.has(key(c.q,c.r)))errors.push(`Duplicate hex ${key(c.q,c.r)}.`);seen.add(key(c.q,c.r));if(!['ground','void'].includes(c.terrain||'ground'))errors.push('Invalid terrain.');if(![null,'tree','wheat','ore','farmstead','forge'].includes(c.object??null))errors.push('Invalid object.');if(!['normal','active','dying','burnt'].includes(c.fire||'normal'))errors.push('Invalid Fire state.');if(c.terrain==='void'&&(c.object||c.fire!=='normal'))errors.push('Void cannot contain an object or Fire.')}for(const fire of def?.scheduledFires||[])if(!def.cells[key(fire.q,fire.r)]||!Number.isInteger(fire.after)||fire.after<1)errors.push('Invalid scheduled Fire.');if(def?.wind&&!byName[def.wind])errors.push('Invalid Wind direction.');if((def?.req?.iron||0)>0&&!def.tools?.includes('forge'))errors.push('Iron goals require Forge.');return{ok:!errors.length,errors}}
  function createInitialState(def){const result=validateDefinition(def);if(!result.ok)throw new Error(result.errors.join(' '));return{definitionId:def.id,moves:def.moves,worldSteps:0,res:{wood:0,wheat:0,charcoal:0,iron:0},cells:clone(def.cells),lost:false,won:false,scheduledFires:clone(def.scheduledFires||[])}}
  function connected(state,q,r,object){const start=at(state,q,r);if(!start||start.object!==object)return[];const queue=[start],seen=new Set([key(q,r)]),out=[];while(queue.length){const current=queue.shift();out.push(current);for(const next of neighbors(current.q,current.r)){const c=at(state,next.q,next.r);if(c&&c.object===object&&!seen.has(key(c.q,c.r))){seen.add(key(c.q,c.r));queue.push(c)}}}return out}
  function cutLine(state,q,r,direction){const out=[];let cq=q,cr=r;for(let n=0;n<3;n++){const c=at(state,cq,cr);if(!normalTree(c))break;out.push(c);[cq,cr]=neighbor(cq,cr,direction)}return out}
  function forgePlan(state,q,r){const center=at(state,q,r);if(!center||center.terrain!=='ground'||center.fire!=='normal'||['ore','farmstead','forge'].includes(center.object))return null;const around=neighbors(q,r).map(x=>at(state,x.q,x.r)).filter(Boolean),fuel=around.filter(normalTree).sort((a,b)=>a.r-b.r||a.q-b.q),starts=around.filter(c=>c.object==='ore').sort((a,b)=>a.r-b.r||a.q-b.q),ore=[],seen=new Set();for(const start of starts)for(const c of connected(state,start.q,start.r,'ore'))if(!seen.has(key(c.q,c.r))){seen.add(key(c.q,c.r));ore.push(c)}ore.sort((a,b)=>a.r-b.r||a.q-b.q);const count=Math.min(fuel.length,ore.length);return{center,fuel:fuel.slice(0,count),ore:ore.slice(0,count),count}}
  const worldActive=state=>Object.values(state.cells).some(c=>c.fire==='active'||c.fire==='dying'||state.scheduledFires.some(f=>!f.fired));
  function getLegalActions(def,state){if(state.lost||state.won)return[];const out=[];if(state.moves>0)for(const c of Object.values(state.cells)){if(def.tools.includes('woodcutter')&&normalTree(c))for(const [direction] of directions)if(cutLine(state,c.q,c.r,direction).length)out.push({tool:'woodcutter',q:c.q,r:c.r,direction});if(def.tools.includes('sickle')&&c.object==='wheat'&&c.fire==='normal')out.push({tool:'sickle',q:c.q,r:c.r});if(def.tools.includes('forge')&&forgePlan(state,c.q,c.r)?.count)out.push({tool:'forge',q:c.q,r:c.r})}if(def.tools.includes('wait')&&worldActive(state))out.push({tool:'wait'});return out}
  function resolveFire(def,state,includeScheduled=true){const active=Object.values(state.cells).filter(c=>c.fire==='active'),dying=Object.values(state.cells).filter(c=>c.fire==='dying'),ignite=new Map(),add=c=>{if(burnable(c))ignite.set(key(c.q,c.r),c)};for(const source of active){for(const next of neighbors(source.q,source.r))add(at(state,next.q,next.r));if(def.wind){const first=neighbor(source.q,source.r,def.wind),middle=at(state,...first),second=middle?.terrain==='void'?null:at(state,...neighbor(first[0],first[1],def.wind));if(middle)add(second)}}if(includeScheduled)for(const fire of state.scheduledFires)if(!fire.fired&&state.worldSteps+1>=fire.after){const c=at(state,fire.q,fire.r);if(c&&c.terrain!=='void'){fire.fired=true;ignite.set(key(c.q,c.r),c)}}for(const c of active)c.fire='dying';for(const c of dying){c.fire='burnt';if(c.object==='tree')state.res.charcoal++;c.object=null}for(const c of ignite.values()){if(c.object==='farmstead')state.lost=true;c.fire='active';if(c.object==='wheat')c.object=null}}
  function updateStatus(def,state){state.won=!state.lost&&Object.entries(def.req||{}).every(([name,amount])=>(state.res[name]||0)>=amount);return state}
  const sig=a=>`${a.tool}:${a.q??''}:${a.r??''}:${a.direction??''}`;
  function applyAction(def,input,action){const state=clone(input);if(!getLegalActions(def,state).some(x=>sig(x)===sig(action)))throw new Error('Illegal hex action.');let log='';if(action.tool==='woodcutter'){const trees=cutLine(state,action.q,action.r,action.direction);for(const c of trees)c.object=null;state.res.wood+=trees.length;state.moves--;log=`WOODCUTTER · start q${action.q}, r${action.r} · ${action.direction} · Trees harvested: ${trees.length}`}if(action.tool==='sickle'){const wheat=connected(state,action.q,action.r,'wheat');for(const c of wheat)c.object=null;state.res.wheat+=wheat.length;state.moves--;log=`SICKLE · region: ${wheat.length} Wheat`}if(action.tool==='forge'){const plan=forgePlan(state,action.q,action.r);plan.center.object='forge';for(const c of plan.fuel)c.object=null;for(const c of plan.ore)c.object=null;state.res.iron+=plan.count;state.moves--;log=`FORGE · q${action.q}, r${action.r} · Fuel: ${plan.fuel.length} · Ore: ${plan.ore.length} · Iron +${plan.count}`}if(action.tool==='wait')log='WAIT';resolveFire(def,state);state.worldSteps++;updateStatus(def,state);return{state,log}}
  function settleFire(def,input){const state=clone(input);while(Object.values(state.cells).some(c=>c.fire==='active'||c.fire==='dying')&&!state.lost)resolveFire(def,state,false);return updateStatus(def,state)}
  function counts(def,state){const actions=getLegalActions(def,state),out={woodcutter:0,forge:0,sickle:0,wait:false,total:actions.length};for(const action of actions)action.tool==='wait'?out.wait=true:out[action.tool]++;return out}
  function directionForDrag(dx,dy,radius,gap=0){if(Math.hypot(dx,dy)<Math.max(18,radius*.55))return null;let best;for(const [name,dq,dr] of directions){const axis=point(dq,dr,radius,gap),score=(dx*axis.x+dy*axis.y)/Math.hypot(axis.x,axis.y);if(!best||score>best.score)best={name,score}}return best.name}
  const token=c=>c.fire==='active'?'🔥':c.fire==='dying'?'♨':c.fire==='burnt'?'●':({tree:'♣',wheat:'✦',ore:'◆',farmstead:'⌂',forge:'⚒'}[c.object]||'');
  function mount(){if(!root.document||document.querySelector('#hexLabScreen'))return;const screen=document.createElement('section');screen.id='hexLabScreen';screen.className='screen';screen.setAttribute('aria-label','Hex Lab developer sandbox');screen.innerHTML='<main class="hex-lab"><p class="eyebrow">Developer gameplay sandbox</p><h1>Hex Lab</h1><p class="hex-copy">Regular pointy-top hexes · one shared-edge rule · isolated from campaign progress.</p><div id="hexLabTests" class="hex-lab-tests"></div><div class="hex-lab-info"><strong id="hexLabTitle"></strong><span id="hexLabHint"></span></div><div id="hexLabResources" class="hex-lab-resources"></div><div id="hexLabBoard" class="hex-board" aria-label="Hex board"></div><div class="hex-lab-tools"><button data-hex-tool="woodcutter">Woodcutter<br><small>Hold, drag, release</small></button><button data-hex-tool="sickle">Sickle<br><small>Wheat region</small></button><button data-hex-tool="forge">Forge<br><small>Six neighbours</small></button><button id="hexLabWait">Wait<br><small>0 moves · world step</small></button></div><div class="hex-lab-actions"><button id="hexLabUndo">Undo</button><button id="hexLabRestart">Restart</button><button id="hexLabBack">Back to game</button></div><details class="hex-lab-debug" open><summary>Action-space debug</summary><p id="hexLabActions"></p><p id="hexLabPreview">Choose a tool, then a hex.</p><ol id="hexLabHistory"></ol></details></main>';document.body.append(screen);
    const style=document.createElement('style');style.textContent='.hex-lab{max-width:620px;margin:auto;padding:18px 12px 44px;color:#373b32}.hex-lab h1{margin:0;font-size:1.7rem}.hex-copy{margin:.3rem 0 .8rem;color:#6f675b}.hex-lab-tests,.hex-lab-tools,.hex-lab-actions{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.hex-lab button{font:inherit;border:1px solid #bcad91;border-radius:10px;padding:9px 10px;background:#fff9ed;color:#3b4034}.hex-lab button.selected{background:#dce8c8;border-color:#758956}.hex-lab button:disabled{opacity:.38}.hex-lab button small{font-size:.68rem;color:#6d6a5c}.hex-lab-info{display:grid;gap:2px;padding:9px 11px;background:#f4eddc;border:1px solid #ddcfb8;border-radius:10px}.hex-lab-info span{font-size:.82rem;color:#70695d}.hex-lab-resources{display:flex;gap:6px;flex-wrap:wrap;margin:9px 0}.hex-lab-resources span{padding:5px 7px;border-radius:7px;background:#f5efe2;border:1px solid #d8c9af;font-size:.75rem;font-weight:700}.hex-board{position:relative;margin:8px auto 12px;background:#d7c49f;border:6px solid #9a7045;border-radius:18px;box-shadow:inset 0 0 0 2px #c69e6d;touch-action:none;overflow:hidden;user-select:none}.hex-tile{position:absolute;display:grid;place-items:center;clip-path:polygon(0 50%,25% 6.699%,75% 6.699%,100% 50%,75% 93.301%,25% 93.301%);background:#91a67b;color:#34442f;font-size:1.35rem;filter:drop-shadow(0 1px 0 #62785755);padding:0;border:0;border-radius:0}.hex-tile.ore{background:#9ca29a}.hex-tile.farmstead{background:#b6a77b}.hex-tile.forge{background:#92978d}.hex-tile.active{background:#d16b38;color:#fff2b6}.hex-tile.dying{background:#855944;color:#f1c68d}.hex-tile.burnt{background:#514f45;color:#817b68}.hex-tile.preview{filter:brightness(1.18) drop-shadow(0 0 0 #f4c85b)}.hex-tile.preview-fuel{background:#d7b75a}.hex-tile.preview-ore{background:#bdd7df}.hex-tile.preview-center{background:#b3c68b}.hex-lab-debug{padding:10px;background:#f5efe2;border:1px solid #ded0ba;border-radius:10px;font-size:.82rem}.hex-lab-debug p{margin:6px 0}.hex-lab-debug ol{margin:7px 0;padding-left:20px}.hex-status{font-weight:800;color:#9c4c32}@media(max-width:390px){.hex-lab{padding-left:8px;padding-right:8px}.hex-lab button{padding:8px}}';document.head.append(style);
    const tests=document.querySelector('#hexLabTests'),board=document.querySelector('#hexLabBoard');let definition=definitions.a,state=createInitialState(definition),history=[],logs=[],tool=null,preview=[],previewKind={},gesture=null,hoverPlan=null,drawRadius=42;
    const clearPreview=()=>{preview=[];previewKind={};hoverPlan=null},setPreview=(cells,kind='')=>{preview=cells;previewKind={};for(const c of cells)previewKind[key(c.q,c.r)]=kind};
    function setDefinition(id){definition=definitions[id];state=createInitialState(definition);history=[];logs=[];tool=null;gesture=null;clearPreview();render()}
    function layout(){const cells=Object.values(state.cells),unit=geometry(1),unitPoints=cells.map(c=>point(c.q,c.r,1)),ux=unitPoints.map(p=>p.x),uy=unitPoints.map(p=>p.y),spanX=Math.max(...ux)-Math.min(...ux)+unit.width,spanY=Math.max(...uy)-Math.min(...uy)+unit.height,availableWidth=Math.max(280,Math.min(580,(root.innerWidth||390)-42)),availableHeight=Math.max(270,Math.min(520,(root.innerHeight||760)*.5));drawRadius=Math.max(20,Math.min(42,availableWidth/spanX,availableHeight/spanY));const g=geometry(drawRadius),ps=cells.map(c=>point(c.q,c.r,drawRadius)),xs=ps.map(p=>p.x),ys=ps.map(p=>p.y);return{cells,g,minX:Math.min(...xs),minY:Math.min(...ys),width:Math.max(...xs)-Math.min(...xs)+g.width+16,height:Math.max(...ys)-Math.min(...ys)+g.height+16}}
    function render(){tests.innerHTML=Object.values(definitions).map(def=>`<button data-hex-test="${def.id}" class="${def.id===definition.id?'selected':''}">${def.title.replace('Test ','')}</button>`).join('');tests.querySelectorAll('[data-hex-test]').forEach(b=>b.onclick=()=>setDefinition(b.dataset.hexTest));document.querySelector('#hexLabTitle').textContent=definition.title;document.querySelector('#hexLabHint').textContent=definition.subtitle;document.querySelector('#hexLabResources').innerHTML=`<span>Moves ${state.moves}</span>${Object.entries(definition.req).map(([n,v])=>`<span>${n} ${state.res[n]||0}/${v}</span>`).join('')}<span>World steps ${state.worldSteps}</span>${state.lost?'<span class="hex-status">Farmstead lost</span>':state.won?'<span class="hex-status">Land secured</span>':''}`;const l=layout();board.style.width=`${l.width}px`;board.style.height=`${l.height}px`;board.innerHTML=l.cells.map(c=>{const p=point(c.q,c.r,drawRadius),k=key(c.q,c.r),mark=preview.some(x=>x.q===c.q&&x.r===c.r)?`preview ${previewKind[k]||''}`:'',classes=['hex-tile',c.object||'',c.fire==='active'?'active':'',c.fire==='dying'?'dying':'',c.fire==='burnt'?'burnt':'',mark].filter(Boolean).join(' ');return`<button class="${classes}" data-q="${c.q}" data-r="${c.r}" style="left:${p.x-l.minX+8}px;top:${p.y-l.minY+8}px;width:${l.g.width}px;height:${l.g.height}px" aria-label="q ${c.q} r ${c.r} ${c.object||'ground'}">${token(c)}</button>`}).join('');document.querySelectorAll('[data-hex-tool]').forEach(b=>{b.hidden=!definition.tools.includes(b.dataset.hexTool);b.classList.toggle('selected',tool===b.dataset.hexTool);b.onclick=()=>{tool=tool===b.dataset.hexTool?null:b.dataset.hexTool;clearPreview();render()}});const c=counts(definition,state);document.querySelector('#hexLabActions').textContent=`LEGAL ACTIONS · Woodcutter: ${c.woodcutter} · Forge: ${c.forge} · Sickle: ${c.sickle} · Wait: ${c.wait?'yes':'no'} · TOTAL: ${c.total}`;document.querySelector('#hexLabPreview').textContent=gesture?(gesture.direction?`Woodcutter ${gesture.direction}: ${preview.length} Tree${preview.length===1?'':'s'} will be cut. Release to commit; return to centre to cancel.`:'Return to the central dead zone to cancel. Drag toward one of six axes to preview.'):hoverPlan?`Forge preview: centre destroys ${hoverPlan.center.object||'Ground'} · ${hoverPlan.fuel.length} Trees → ${hoverPlan.ore.length} Iron.`:'Choose a tool, then a hex.';document.querySelector('#hexLabHistory').innerHTML=logs.map(x=>`<li>${x}</li>`).join('');document.querySelector('#hexLabUndo').disabled=!history.length}
    const eventCell=e=>{const t=e.target.closest?.('.hex-tile');return t?at(state,+t.dataset.q,+t.dataset.r):null};
    function previewForge(c){const plan=c&&forgePlan(state,c.q,c.r);if(!plan)return;hoverPlan=plan;preview=[plan.center,...plan.fuel,...plan.ore];previewKind={[key(plan.center.q,plan.center.r)]:'preview-center'};for(const x of plan.fuel)previewKind[key(x.q,x.r)]='preview-fuel';for(const x of plan.ore)previewKind[key(x.q,x.r)]='preview-ore';render()}
    board.onpointerdown=e=>{const c=eventCell(e);if(tool==='woodcutter'&&normalTree(c)){const rect=board.getBoundingClientRect();gesture={q:c.q,r:c.r,x:e.clientX-rect.left,y:e.clientY-rect.top,pointerId:e.pointerId,direction:null};board.setPointerCapture?.(e.pointerId);clearPreview();e.preventDefault();render()}};
    board.onpointermove=e=>{if(gesture){const rect=board.getBoundingClientRect(),d=directionForDrag(e.clientX-rect.left-gesture.x,e.clientY-rect.top-gesture.y,drawRadius);if(d!==gesture.direction){gesture.direction=d;d?setPreview(cutLine(state,gesture.q,gesture.r,d)):clearPreview();render()}return}if(tool==='forge'&&e.pointerType!=='touch'){const c=eventCell(e),plan=c&&forgePlan(state,c.q,c.r);if(plan&&(!hoverPlan||hoverPlan.center.q!==plan.center.q||hoverPlan.center.r!==plan.center.r))previewForge(c)}};
    board.onpointerup=e=>{if(gesture&&e.pointerId===gesture.pointerId){const done=gesture;gesture=null;if(done.direction&&preview.length)commit({tool:'woodcutter',q:done.q,r:done.r,direction:done.direction});else{clearPreview();render()}board.releasePointerCapture?.(e.pointerId);return}const c=eventCell(e);if(!c)return;if(tool==='sickle')commit({tool:'sickle',q:c.q,r:c.r});if(tool==='forge')commit({tool:'forge',q:c.q,r:c.r})};board.onpointercancel=()=>{gesture=null;clearPreview();render()};
    function commit(action){try{history.push(clone(state));const result=applyAction(definition,state,action);state=result.state;logs.push(result.log);if(logs.length>30)logs.shift();tool=null;gesture=null;clearPreview();render()}catch(error){clearPreview();render();document.querySelector('#hexLabPreview').textContent=error.message}}
    document.querySelector('#hexLabWait').onclick=()=>commit({tool:'wait'});document.querySelector('#hexLabUndo').onclick=()=>{const prior=history.pop();if(prior)state=prior;logs.pop();tool=null;gesture=null;clearPreview();render()};document.querySelector('#hexLabRestart').onclick=()=>setDefinition(definition.id);document.querySelector('#hexLabBack').onclick=()=>root.SootSeedHexProduction?.showCampaign?.()||root.SootSeedGame.showMenu();const controls=document.querySelector('.campaign-debug');if(controls){const b=document.createElement('button');b.type='button';b.textContent='Hex Lab';b.onclick=()=>{setDefinition('a');root.SootSeedGame.showScreen('hexLabScreen')};controls.append(b)}root.addEventListener?.('resize',()=>render());render()}
  root.SootSeedHexLab={SQRT3,directions,definitions,key,neighbor,neighbors,geometry,point,validateDefinition,createInitialState,connected,cutLine,forgePlan,getLegalActions,resolveFire,settleFire,applyAction,counts,directionForDrag,mount};if(root.document)mount()
})(globalThis);
