const fs=require('fs'),assert=require('assert/strict'),sim=require(require('path').join(__dirname,'../game-simulation.js'));global.SootSeedSimulation=sim;require(require('path').join(__dirname,'../level-lab/solver.js'));const src=fs.readFileSync(require('path').join(__dirname,'../wait-campaign.js'),'utf8'),line=src.split('\n').find(x=>x.includes("id:'windfall-20"));const level=Function('return '+line.trim().replace(/,$/,''))();level.map=level.map.map(r=>r.replace(/\d/g,'.'));const start=sim.createInitialState(level);assert.equal(start.cells.flat().filter(x=>x.object==='tree').length,19);assert.equal(sim.region(start,1,3,'tree').length,19);const placements=sim.getLegalActions(level,start).filter(a=>a.tool==='forge').map(a=>({...a,...sim.calculateForgeResult(start,a.r,a.c)}));
function search(noWait=false){let seen=new Set(),wins=[],nodes=0;function visit(s,path){const key=SootSeedLevelLabSolver.stateHash(s);if(seen.has(key))return;seen.add(key);nodes++;if(sim.getGameStatus(level,s).won){wins.push({path,res:s.res,moves:s.moves,actions:s.actions});return;}if(s.houseLost||s.moves<=0)return;const trees=s.cells.flat().filter(x=>x.object==='tree').length,pending=s.cells.flat().filter(x=>x.charcoalPending).length;if(s.res.wood+trees<9||s.res.charcoal+trees+pending<7||s.res.iron+s.cells.flat().filter(x=>x.object==='ore').length<3)return;for(const a of SootSeedLevelLabSolver.canonicalActions(level,s)){if(noWait&&a.tool==='wait')continue;visit(sim.applyAction(level,s,a).state,[...path,a]);}}visit(start,[]);return {nodes,wins};}const all=search(),noWait=search(true);assert(all.wins.length>0);assert.equal(noWait.wins.length,0);assert(placements.some(p=>p.count===4));assert.equal(placements.length,12);
for(const win of all.wins){assert.equal(win.moves,0);assert.deepEqual(win.res,{wood:9,charcoal:7,wheat:4,iron:3});assert(win.path.some(a=>a.tool==='wait'));assert.equal(win.path.filter(a=>a.tool!=='wait').length,4);}
let state=start,events=[];for(const action of all.wins[0].path){if(action.tool==='forge'){const preview=sim.calculateForgeResult(state,action.r,action.c),result=sim.applyAction(level,state,action);assert.deepEqual(result.event.forge,preview);assert(!preview.fuel.some(([r,c])=>r===action.r&&c===action.c));state=result.state;events.push(result.event);}else{const result=sim.applyAction(level,state,action);state=result.state;events.push(result.event);}}
assert(!state.houseLost);assert(sim.getGameStatus(level,state).won);assert.equal(sim.activeFireCells(state).length,0);assert.equal(sim.dyingFireCells(state).length,0);
assert.deepEqual(events[2].world.scheduled,[[6,3]]);assert(events.slice(0,2).every(e=>e.world.scheduled.length===0));// Authored-board limitation: the reference win harvests the lower Forest before
// scheduled Fire spreads; UP wind therefore adds no targets in this win.
assert(events.every(e=>e.world.wind.length===0));
assert(events[0].world.activeToDying.length>0);assert.equal(events[0].world.charcoal,0);assert.equal(events[1].world.charcoal,0);assert(events[2].world.charcoal>0);assert(events[2].world.dyingToBurnt.length>0);
// Final Fire Resolution settles the remaining delayed Charcoal after move four.
assert(state.res.charcoal>events.reduce((n,e)=>n+e.world.charcoal,0));
// Waiting without reshaping the Forest eventually loses the real Farmstead.
let unsafe=start;for(let i=0;i<12&&!unsafe.houseLost&&sim.canWait(unsafe);i++)unsafe=sim.applyAction(level,unsafe,{tool:'wait'}).state;assert(unsafe.houseLost);
// Maximum output consumes too much of the exact 19-Tree budget, even before center destruction.
for(const p of placements.filter(p=>p.count===4)){const next=sim.applyAction(level,start,p).state;const trees=next.cells.flat().filter(c=>c.object==='tree').length,pending=next.cells.flat().filter(c=>c.charcoalPending).length;assert(trees+pending+next.res.wood+next.res.charcoal<16);}
// Initial Woodcut consumes the sole Forest; neither Iron nor Charcoal can then reach its goal.
const greedy=sim.applyAction(level,start,{tool:'woodcutter',r:1,c:3}).state;assert.equal(greedy.res.wood,19);assert.equal(sim.getLegalActions(level,greedy).filter(a=>a.tool==='forge').length,0);
// WIND UP jumps over non-void Ground, using the same engine as the campaign.
const windLevel={moves:1,wind:'up',req:{charcoal:1},tools:['wait'],map:['T','.','F']};const wind=sim.applyAction(windLevel,sim.createInitialState(windLevel),{tool:'wait'});assert.deepEqual(wind.event.world.wind,[[0,0]]);assert.equal(wind.state.cells[0][0].state,'active-fire');assert.equal(wind.state.res.charcoal,0);
console.log(JSON.stringify({connectedTrees:19,forgePlacements:placements.length,searchStates:all.nodes,noWaitStates:noWait.nodes,winningStateRepresentatives:all.wins.length,solution:all.wins[0]},null,2));
