const assert=require('node:assert/strict');
const sim=require('../game-simulation.js');globalThis.SootSeedSimulation=sim;
for(const name of ['types','rng','candidates','validation','mutations','solver','agents','analysis','generation','candidate-store','qd-search'])require(`../level-lab/${name}.js`);
const level={name:'QD smoke',moves:2,req:{wood:1,charcoal:1},tools:['woodcutter','wait'],map:['FT.','...']};
const seed=SootSeedLevelLabCandidates.createCandidate('qd-smoke',level,{id:'qd-root'});
const fakeAnalysis=(constraint,separation)=>({difficulty:{constraint,execution:.4,timing:.1,resourcePlanning:0,forge:0,fireAwareness:0},strategicSignals:{strategySeparation:separation,solutionNarrowness:.3,agentDisagreement:separation,oracleHumanGap:.2,greedyPunishment:0},solutionFlexibility:{successfulFirstActionEntropy:.7},tags:[]});
assert.deepEqual(SootSeedLevelLabQD.cellFor(fakeAnalysis(0,0),'general',5),{preset:'general',x:0,y:0,xBucket:0,yBucket:0,key:'0,0',buckets:5},'zero maps to first archive cell');
assert.equal(SootSeedLevelLabQD.cellFor(fakeAnalysis(1,1),'general',5).key,'4,4','one maps to final archive cell');
const archive=SootSeedLevelLabQD.createArchive(level,{archivePreset:'general',buckets:5});
const solved={...seed,id:'elite-a',evaluation:{status:'solved',oracle:{status:'SOLVED',paidMoves:1},agents:[],analysis:fakeAnalysis(.5,.5)}};
const accepted=archive.insert(solved,0);assert(accepted.inserted,'empty archive cell accepts candidate');
const retained=archive.insert({...solved,id:'elite-b'},1);assert.equal(retained.inserted,false,'equal-quality candidate does not displace existing elite');
assert.equal(archive.coverage(),1/25,'archive coverage is exact');
const searchA=SootSeedLevelLabQD.createSearch({seedCandidate:seed,searchSeed:'qd-repeat',generations:2,childrenPerGeneration:4,mutationDepthMax:1,oraclePreset:'fast',ensemblePreset:'quick'});
const searchB=SootSeedLevelLabQD.createSearch({seedCandidate:seed,searchSeed:'qd-repeat',generations:2,childrenPerGeneration:4,mutationDepthMax:1,oraclePreset:'fast',ensemblePreset:'quick'});
(async()=>{
  let yields=0;await SootSeedLevelLabQD.runSearch(searchA,{onProgress(){yields++;}});await SootSeedLevelLabQD.runSearch(searchB);
  assert.equal(searchA.status,'completed','configured generations terminate');
  assert(yields>0,'search reports incremental progress');
  assert.deepEqual(searchA.candidates.map(c=>c.metadata?.fingerprint),searchB.candidates.map(c=>c.metadata?.fingerprint),'chunked search remains deterministic');
  const searchDifferent=SootSeedLevelLabQD.createSearch({seedCandidate:seed,searchSeed:'qd-different',generations:2,childrenPerGeneration:4,mutationDepthMax:1,oraclePreset:'fast',ensemblePreset:'quick'});await SootSeedLevelLabQD.runSearch(searchDifferent);assert.notDeepEqual(searchA.candidates.map(c=>c.metadata?.fingerprint),searchDifferent.candidates.map(c=>c.metadata?.fingerprint),'different search seeds explore a different candidate sequence');
  assert(searchA.candidates.filter(c=>c.generation>1).every(c=>c.parentId),'later generations track a parent');
  const later=searchA.candidates.find(c=>c.generation>1);if(later)assert(SootSeedLevelLabQD.lineage(searchA,later.id).length>=2,'lineage reconstructs ancestors');
  const projection=SootSeedLevelLabQD.project(searchA,'timing');assert(projection&&projection.presetId==='timing','archive can be reprojected without rerunning simulation');
  const cancel=SootSeedLevelLabQD.createSearch({seedCandidate:seed,searchSeed:'cancel',generations:5,childrenPerGeneration:5,mutationDepthMax:1,oraclePreset:'fast',ensemblePreset:'quick'});await SootSeedLevelLabQD.runSearch(cancel,{onProgress(){cancel.cancelToken.cancelled=true;}});assert.equal(cancel.status,'cancelled','cancellation retains a safe partial archive');
  assert.deepEqual(level,{name:'QD smoke',moves:2,req:{wood:1,charcoal:1},tools:['woodcutter','wait'],map:['FT.','...']},'QD search never mutates campaign-like seed data');
  const originalStorage=globalThis.localStorage;let data={};globalThis.localStorage={getItem:key=>data[key]||null,setItem:(key,value)=>{data[key]=value;}};SootSeedLevelLabCandidateStore.add(solved);SootSeedLevelLabCandidateStore.pin('elite-a');const saved=JSON.parse(data[SootSeedLevelLabCandidateStore.storageKey]);assert.equal(saved.version,1,'pinned candidate uses the versioned persistence schema');assert.equal(saved.candidates[0].metadata?.fingerprint,undefined,'persistence does not synthesize or alter candidate data');data[SootSeedLevelLabCandidateStore.storageKey]='not-json';assert.deepEqual(SootSeedLevelLabCandidateStore.restore(),[],'malformed saved candidate data fails safely');data[SootSeedLevelLabCandidateStore.storageKey]=JSON.stringify({version:999,candidates:[solved]});assert.deepEqual(SootSeedLevelLabCandidateStore.restore(),[],'unknown saved candidate schema is ignored safely');globalThis.localStorage=originalStorage;
  console.log('Level Lab QD tests passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
