(function(root){
const sim=root.SootSeedSimulation,canon=()=>root.SootSeedLevelLabSolver.canonicalActions;
const defs=[['balanced','Balanced','Balances goals, danger and options.',2,0.15,{progress:5,yield:1,forge:2,wait:1,safe:2}],['greedy-harvester','Greedy Harvester','Chases immediate visible gains.',1,.35,{progress:7,yield:3,forge:1,wait:-2,safe:.2}],['max-yield','Max Yield','Does the biggest available thing.',1,.3,{progress:2,yield:6,forge:3,wait:-2,safe:.2}],['forge-first','Forge First','Strongly favours useful Iron.',2,.2,{progress:3,yield:1,forge:8,wait:.2,safe:1}],['requirement-chaser','Requirement Chaser','Targets the largest remaining deficit.',2,.2,{progress:8,yield:1,forge:4,wait:.5,safe:1}],['fire-fearful','Fire Fearful','Protects threatened needed resources.',2,.2,{progress:4,yield:1,forge:1,wait:1,safe:8}],['wait-friendly','Wait Friendly','Lets productive Fire timing resolve.',2,.25,{progress:3,yield:1,forge:2,wait:6,safe:3}],['action-conservator','Action Conservator','Spends paid moves only for value.',2,.2,{progress:4,yield:4,forge:2,wait:4,safe:2}]];
function score(level,state,action,w){const next=sim.applyAction(level,state,action).state,status=sim.getGameStatus(level,next);if(status.lost)return-1e6;if(status.won)return 1e6;let progress=0,yielded=0;for(const k of ['wood','charcoal','wheat','iron']){const delta=next.res[k]-state.res[k],need=Math.max(0,(level.req[k]||0)-state.res[k]);progress+=Math.min(delta,need);yielded+=delta;}const forge=action.tool==='forge'?next.res.iron-state.res.iron:0;const fireBefore=sim.activeFireCells(state).length+sim.dyingFireCells(state).length,fireAfter=sim.activeFireCells(next).length+sim.dyingFireCells(next).length;const safe=fireBefore-fireAfter+(next.res.charcoal-state.res.charcoal);const wait=action.tool==='wait'?(yielded+fireBefore?1:-1):0;return w.progress*progress+w.yield*yielded+w.forge*forge+w.wait*wait+w.safe*safe;}
function chooseAction(agent,level,state,rng){const actions=canon()(level,state);if(!actions.length)return null;const scored=actions.map(action=>({action,value:score(level,state,action,agent.weights)}));for(const item of scored){let future=0,probe=sim.applyAction(level,state,item.action).state;if(agent.lookaheadDepth>1){const next=canon()(level,probe);if(next.length)future=Math.max(...next.map(a=>score(level,probe,a,agent.weights)))*.35;}item.value+=future+(rng.next()-.5)*agent.temperature;}scored.sort((a,b)=>b.value-a.value||root.SootSeedLevelLabSolver.actionId(a.action).localeCompare(root.SootSeedLevelLabSolver.actionId(b.action)));return{action:scored[0].action,scored};}
const agents=defs.map(([id,name,description,lookaheadDepth,temperature,weights])=>({id,name,description,lookaheadDepth,temperature,weights,chooseAction}));
function attempt(level,agent,seed,limits={}){const rng=root.SootSeedLevelLabRng.createSeededRng(seed),max=limits.maxActionsPerAttempt??40;let state=sim.createInitialState(level),actions=[],waits=0;const seen=new Set();for(let i=0;i<max;i++){const h=root.SootSeedLevelLabSolver.stateHash(state);if(seen.has(h))return finish('LOOP_DETECTED');seen.add(h);if(sim.getGameStatus(level,state).won)return finish('WIN');if(sim.getGameStatus(level,state).lost)return finish('LOSS');const pick=chooseAction(agent,level,state,rng);if(!pick)return finish('NO_LEGAL_ACTION');actions.push(pick.action);if(pick.action.tool==='wait')waits++;state=sim.applyAction(level,state,pick.action).state;}return finish('ACTION_LIMIT_REACHED');function finish(reason){const s=sim.getGameStatus(level,state);return{agentId:agent.id,seed,reason,won:s.won,actions,firstAction:actions[0]?root.SootSeedLevelLabSolver.actionId(actions[0]):null,paidMoves:s.paidMovesUsed,worldSteps:s.worldSteps,waits};}}
function runEnsemble(level,{attempts=10,seed='12345'}={}){return agents.map(agent=>{const runs=Array.from({length:attempts},(_,i)=>attempt(level,agent,`${seed}:${agent.id}:${i}`));const wins=runs.filter(r=>r.won),first={};runs.forEach(r=>{if(r.firstAction)first[r.firstAction]=(first[r.firstAction]||0)+1});const top=Object.entries(first).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]||'—';return{agent,attempts,wins:wins.length,winRate:wins.length/attempts,averagePaidMoves:runs.reduce((n,r)=>n+r.paidMoves,0)/attempts,averageWaits:runs.reduce((n,r)=>n+r.waits,0)/attempts,topFirstAction:top,firstActions:first,runs};});}
root.SootSeedLevelLabAgents={agents,chooseAction,simulateAgentAttempt:attempt,runEnsemble};
})(globalThis);
