(function(root){
  // Human-like evaluation only: every hypothetical state is produced by the shared game simulation.
  const sim=root.SootSeedSimulation, canonical=()=>root.SootSeedLevelLabSolver.canonicalActions;
  const actionId=action=>root.SootSeedLevelLabSolver.actionId(action),resourceKinds=['wood','charcoal','wheat','iron'];
  const definitions=[
    ['balanced','Balanced','Balances requirements, danger, future options and efficient moves.',2,.15,{progress:5,yield:1,forge:2,wait:1,safe:2,move:1,options:1}],
    ['greedy-harvester','Greedy Harvester','Chases immediate visible resource gains.',1,.35,{progress:7,yield:3,forge:1,wait:-2,safe:.2,move:.2,options:0}],
    ['max-yield','Max Yield','Prefers the largest immediately affected region.',1,.3,{progress:2,yield:6,forge:3,wait:-2,safe:.2,move:.2,options:0}],
    ['forge-first','Forge First','Strongly favours meaningful Iron-producing Forge opportunities.',2,.2,{progress:3,yield:1,forge:8,wait:.2,safe:1,move:.5,options:1}],
    ['requirement-chaser','Requirement Chaser','Targets the greatest normalized remaining requirement.',2,.2,{progress:8,yield:1,forge:4,wait:.5,safe:1,move:.5,options:1}],
    ['fire-fearful','Fire Fearful','Protects required resources threatened by Fire.',2,.2,{progress:4,yield:1,forge:1,wait:1,safe:8,move:.5,options:1}],
    ['wait-friendly','Wait Friendly','Waits when Fire timing can productively resolve.',2,.25,{progress:3,yield:1,forge:2,wait:6,safe:3,move:.5,options:1}],
    ['action-conservator','Action Conservator','Avoids paid moves unless their payoff is convincing.',2,.2,{progress:4,yield:4,forge:2,wait:4,safe:2,move:4,options:1}]
  ];
  const agents=definitions.map(([id,name,description,lookaheadDepth,temperature,weights])=>({id,name,description,lookaheadDepth,temperature,weights,chooseAction}));
  function requirementsProgress(level,state,next){let needed=0,yielded=0,normalized=0;for(const kind of resourceKinds){const gain=(next.res[kind]||0)-(state.res[kind]||0),remaining=Math.max(0,(level.req[kind]||0)-(state.res[kind]||0));needed+=Math.min(gain,remaining);yielded+=gain;if(level.req[kind])normalized+=Math.min(gain,remaining)/level.req[kind];}return{needed,yielded,normalized};}
  function scoreAction(level,state,action,weights){const next=sim.applyAction(level,state,action).state,status=sim.getGameStatus(level,next);if(status.lost)return{value:-1000000,next,signals:{lost:1}};if(status.won)return{value:1000000,next,signals:{won:1}};const resources=requirementsProgress(level,state,next),forge=action.tool==='forge'?next.res.iron-state.res.iron:0,beforeFire=sim.activeFireCells(state).length+sim.dyingFireCells(state).length,afterFire=sim.activeFireCells(next).length+sim.dyingFireCells(next).length,wait=action.tool==='wait'?(resources.yielded+beforeFire>0?1:-1):0,paid=Math.max(0,state.moves-next.moves),options=canonical()(level,next).length,region=action.tool==='sickle'||action.tool==='woodcutter'?sim.region(state,action.r,action.c,action.tool==='sickle'?'wheat':'tree').length:0,signals={progress:resources.needed+resources.normalized,yield:resources.yielded,forge,safe:beforeFire-afterFire+(next.res.charcoal-state.res.charcoal),wait,move:paid,options,region};return{value:weights.progress*signals.progress+weights.yield*(signals.yield+region*.2)+weights.forge*forge+weights.wait*wait+weights.safe*signals.safe-weights.move*paid+weights.options*Math.min(5,options)*.1,next,signals};}
  function chooseAction(agent,level,state,rng){const actions=canonical()(level,state);if(!actions.length)return null;const scored=actions.map(action=>({action,...scoreAction(level,state,action,agent.weights)}));for(const entry of scored){const following=agent.lookaheadDepth>1?canonical()(level,entry.next):[];entry.lookahead=following.length?Math.max(...following.map(action=>scoreAction(level,entry.next,action,agent.weights).value))*.35:0;entry.noise=(rng.next()-.5)*agent.temperature;entry.total=entry.value+entry.lookahead+entry.noise;}scored.sort((a,b)=>b.total-a.total||actionId(a.action).localeCompare(actionId(b.action)));return{action:scored[0].action,scored};}
  function simulateAgentAttempt(level,agent,seed,limits={}){const rng=root.SootSeedLevelLabRng.createSeededRng(seed),maxActions=limits.maxActionsPerAttempt??40,maxWorldSteps=limits.maxWorldSteps??80,maxRepeated=limits.maxRepeatedEquivalentStates??1;let state=sim.createInitialState(level),waits=0;const actions=[],trace=[],seen=new Map();for(let step=0;step<maxActions;step++){const key=root.SootSeedLevelLabSolver.stateHash(state),visits=(seen.get(key)||0)+1;seen.set(key,visits);if(visits>maxRepeated)return finish('LOOP_DETECTED');const status=sim.getGameStatus(level,state);if(status.won)return finish('WIN');if(status.lost)return finish('LOSS');if(status.worldSteps>=maxWorldSteps)return finish('WORLD_STEP_LIMIT_REACHED');const pick=chooseAction(agent,level,state,rng);if(!pick)return finish('NO_LEGAL_ACTION');actions.push(pick.action);if(pick.action.tool==='wait')waits++;trace.push({step:step+1,chosen:actionId(pick.action),scores:pick.scored.map(item=>({action:actionId(item.action),score:+item.total.toFixed(4),signals:item.signals}))});state=sim.applyAction(level,state,pick.action).state;}return finish('ACTION_LIMIT_REACHED');function finish(reason){const status=sim.getGameStatus(level,state);return{agentId:agent.id,seed,reason,won:status.won,actions,trace,firstAction:actions[0]?actionId(actions[0]):null,paidMoves:status.paidMovesUsed,worldSteps:status.worldSteps,waits,finalResources:{...state.res},finalRequirementCompletion:requirementsProgress(level,sim.createInitialState(level),state).normalized};}}
  function aggregateAgent(agent,runs){const wins=runs.filter(run=>run.won),firstActions={},terminationReasons={},sequenceCounts={};for(const run of runs){if(run.firstAction)firstActions[run.firstAction]=(firstActions[run.firstAction]||0)+1;terminationReasons[run.reason]=(terminationReasons[run.reason]||0)+1;if(run.won){const sequence=run.actions.map(actionId).join(' → ');sequenceCounts[sequence]=(sequenceCounts[sequence]||0)+1;}}const average=values=>values.reduce((sum,value)=>sum+value,0)/runs.length,ordered=object=>Object.entries(object).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));return{agent,attempts:runs.length,wins:wins.length,losses:runs.length-wins.length,winRate:wins.length/runs.length,averagePaidMoves:average(runs.map(run=>run.paidMoves)),averageActions:average(runs.map(run=>run.actions.length)),averageWorldSteps:average(runs.map(run=>run.worldSteps)),averageWaits:average(runs.map(run=>run.waits)),averageRequirementCompletion:average(runs.map(run=>run.finalRequirementCompletion)),topFirstAction:ordered(firstActions)[0]?.[0]||'—',firstActions,terminationReasons,runs,distinctWinningSequences:Object.keys(sequenceCounts).length,mostCommonWinningSequence:ordered(sequenceCounts)[0]?.[0]||null,fastestSuccessfulRun:wins.sort((a,b)=>a.actions.length-b.actions.length||a.paidMoves-b.paidMoves)[0]||null};}
  function compareWithOracle(results,oracle){if(!oracle)return null;const oracleFirst=oracle.solutionActions?.[0]?actionId(oracle.solutionActions[0]):null;return{status:oracle.status,solvable:oracle.solvable,minimumPaidMoves:oracle.paidMoves,firstAction:oracleFirst,agents:results.map(result=>{const successful=result.runs.filter(run=>run.won),best=successful.reduce((best,run)=>!best||run.paidMoves<best.paidMoves?run:best,null);return{agentId:result.agent.id,bestPaidMoves:best?.paidMoves??null,paidMoveGap:best&&oracle.solvable?best.paidMoves-oracle.paidMoves:null,optimalWins:oracle.solvable?successful.filter(run=>run.paidMoves===oracle.paidMoves).length:0,firstActionAgreement:oracleFirst?result.runs.filter(run=>run.firstAction===oracleFirst).length:0};})};}
  function runEnsemble(level,{attempts=10,seed='12345',limits={}}={}){return agents.map(agent=>aggregateAgent(agent,Array.from({length:attempts},(_,index)=>simulateAgentAttempt(level,agent,`${seed}:${agent.id}:${index}`,limits))));}
  root.SootSeedLevelLabAgents={agents,scoreAction,chooseAction,simulateAgentAttempt,runEnsemble,compareWithOracle};
})(globalThis);
