/* Design descriptors built only from Oracle and human-agent results. Thresholds are provisional. */
(function(root){
  const thresholds={highWinRate:.8,lowWinRate:.25,strongContrast:.35,highConsensus:.75,forcedSuccessShare:.8,forcedAlternativeAttempts:.2,trapPopularity:.2,trapWinRate:.15,trapWinningAlternative:.5,openEntropy:.65,obviousWinRate:.9};
  const resultCache=new Map();
  const clamp=value=>Math.max(0,Math.min(1,value));
  const average=values=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;
  const median=values=>{const sorted=[...values].sort((a,b)=>a-b);return sorted.length?sorted[Math.floor(sorted.length/2)]:null;};
  const entropy=counts=>{const total=Object.values(counts).reduce((sum,value)=>sum+value,0),n=Object.keys(counts).length;if(!total||n<2)return 0;return -Object.values(counts).reduce((sum,value)=>{const p=value/total;return sum+(p? p*Math.log2(p):0);},0)/Math.log2(n);};
  const byAgent=(ensemble,id)=>ensemble.find(result=>result.agent.id===id)||null;
  const actionName=action=>action||'—';
  function openingAnalysis(ensemble,oracle){
    const openings={},allRuns=ensemble.flatMap(result=>result.runs.map(run=>({...run,agentId:result.agent.id,agentName:result.agent.name})));
    for(const run of allRuns){if(!run.firstAction)continue;const item=openings[run.firstAction]||(openings[run.firstAction]={action:run.firstAction,attempts:0,wins:0,agents:[],oracleOpening:false});item.attempts++;if(run.won)item.wins++;if(!item.agents.includes(run.agentName))item.agents.push(run.agentName);}
    const oracleOpening=oracle?.solutionActions?.[0]?root.SootSeedLevelLabSolver.actionId(oracle.solutionActions[0]):null;
    const total=allRuns.length,successes=allRuns.filter(run=>run.won).length;
    const items=Object.values(openings).map(item=>({...item,winRate:item.attempts?item.wins/item.attempts:0,attemptShare:total?item.attempts/total:0,successShare:successes?item.wins/successes:0,oracleOpening:item.action===oracleOpening})).sort((a,b)=>b.attempts-a.attempts||a.action.localeCompare(b.action));
    const best=Math.max(0,...items.map(item=>item.winRate));
    const traps=items.filter(item=>item.attemptShare>=thresholds.trapPopularity&&item.attempts>=2&&item.winRate<=thresholds.trapWinRate&&best>=thresholds.trapWinningAlternative);
    const winning=items.filter(item=>item.wins>0),topWinning=[...winning].sort((a,b)=>b.successShare-a.successShare||a.action.localeCompare(b.action))[0]||null;
    const alternatives=items.filter(item=>item.action!==topWinning?.action).reduce((sum,item)=>sum+item.attemptShare,0);
    const forced=!!topWinning&&items.length>1&&topWinning.successShare>=thresholds.forcedSuccessShare&&alternatives>=thresholds.forcedAlternativeAttempts&&items.filter(item=>item.action!==topWinning.action).every(item=>item.winRate<=thresholds.trapWinRate);
    return{items,totalAttempts:total,totalSuccesses:successes,firstActionEntropy:entropy(Object.fromEntries(items.map(item=>[item.action,item.attempts]))),successfulFirstActionEntropy:entropy(Object.fromEntries(items.map(item=>[item.action,item.wins]))),winningFirstActionCount:winning.length,topOpening:items[0]?.action||null,topWinningOpening:topWinning?.action||null,traps,forced};
  }
  function analyzeFromResults(level,{oracle=null,ensemble=null}={}){
    if(!Array.isArray(ensemble)||!ensemble.length)return{available:false,tags:[],warnings:['Run the human-agent ensemble before analysis.'],thresholds};
    const rates=ensemble.map(result=>result.winRate),allRuns=ensemble.flatMap(result=>result.runs),wins=allRuns.filter(run=>run.won),balanced=byAgent(ensemble,'balanced'),greedy=byAgent(ensemble,'greedy-harvester'),maxYield=byAgent(ensemble,'max-yield'),forge=byAgent(ensemble,'forge-first'),wait=byAgent(ensemble,'wait-friendly'),fire=byAgent(ensemble,'fire-fearful'),requirement=byAgent(ensemble,'requirement-chaser'),conservator=byAgent(ensemble,'action-conservator');
    const openings=openingAnalysis(ensemble,oracle),overallWinRate=wins.length/allRuns.length,successfulArchetypeCount=ensemble.filter(result=>result.wins>0).length,moveOnWin=average(wins.map(run=>run.paidMoves)),actionsOnWin=average(wins.map(run=>run.actions.length)),waits=average(allRuns.map(run=>run.waits));
    const oracleMoves=oracle?.solvable?oracle.paidMoves:null,oracleOpening=oracle?.solutionActions?.[0]?root.SootSeedLevelLabSolver.actionId(oracle.solutionActions[0]):null,oracleAgreementRate=oracleOpening?allRuns.filter(run=>run.firstAction===oracleOpening).length/allRuns.length:null,oracleMoveGap=oracleMoves===null||moveOnWin===null?null:moveOnWin-oracleMoves;
    const contrasts={balancedVsGreedy:balanced&&greedy?balanced.winRate-greedy.winRate:null,balancedVsMaxYield:balanced&&maxYield?balanced.winRate-maxYield.winRate:null,forgeVsGreedy:forge&&greedy?forge.winRate-greedy.winRate:null,waitVsGreedy:wait&&greedy?wait.winRate-greedy.winRate:null,fireVsGreedy:fire&&greedy?fire.winRate-greedy.winRate:null,requirementVsMaxYield:requirement&&maxYield?requirement.winRate-maxYield.winRate:null,conservatorVsGreedy:conservator&&greedy?conservator.winRate-greedy.winRate:null};
    const usesForge=oracle?.solutionActions?.some(action=>action.tool==='forge')||false,forgeRelevant=usesForge||(level.req?.iron||0)>0,usesWait=oracle?.solutionActions?.some(action=>action.tool==='wait')||false;
    const maxContrast=Math.max(0,...Object.values(contrasts).filter(value=>value!==null).map(value=>Math.abs(value)));
    const flexibilityEntropy=openings.successfulFirstActionEntropy,sequenceCounts={};wins.forEach(run=>{const key=run.actions.map(root.SootSeedLevelLabSolver.actionId).join(' → ');sequenceCounts[key]=(sequenceCounts[key]||0)+1;});const distinctSequences=Object.keys(sequenceCounts).length,commonSequenceShare=wins.length?Math.max(...Object.values(sequenceCounts))/wins.length:0;
    const difficulty={execution:clamp(1-overallWinRate),constraint:clamp((1-flexibilityEntropy)*.65+(openings.winningFirstActionCount<=1?.35:0)),optimality:oracleMoveGap===null?null:clamp(oracleMoveGap/Math.max(1,oracleMoves||1)),timing:clamp(Math.max(usesWait?.25:0,contrasts.waitVsGreedy||0,contrasts.fireVsGreedy||0)),resourcePlanning:clamp(Math.max(contrasts.balancedVsGreedy||0,contrasts.balancedVsMaxYield||0,contrasts.requirementVsMaxYield||0)),forge:forgeRelevant?clamp(Math.max(usesForge?.25:0,contrasts.forgeVsGreedy||0)):0,fireAwareness:clamp(Math.max(contrasts.fireVsGreedy||0,contrasts.waitVsGreedy||0))};
    const tags=[];if(openings.forced)tags.push('FORCED_OPENING');if(openings.traps.length)tags.push('TRAP_OPENING');if(contrasts.balancedVsGreedy>=thresholds.strongContrast||contrasts.balancedVsMaxYield>=thresholds.strongContrast)tags.push('GREEDY_TRAP');if(difficulty.timing>=thresholds.strongContrast)tags.push('TIMING_SENSITIVE');if(usesForge&&contrasts.forgeVsGreedy>=thresholds.strongContrast)tags.push('FORGE_INSIGHT');if(maxContrast>=thresholds.strongContrast)tags.push('STRATEGY_SELECTIVE');if(openings.firstActionEntropy<=.25&&openings.topOpening)tags.push('HIGH_CONSENSUS');if(overallWinRate>=thresholds.obviousWinRate&&openings.firstActionEntropy<=.25&&difficulty.constraint<.5&&difficulty.optimality!==null&&difficulty.optimality<=.1)tags.push('OBVIOUS_SOLUTION');if(openings.winningFirstActionCount>=2&&flexibilityEntropy>=thresholds.openEntropy)tags.push('OPEN_STRATEGY');
    const flexibility=flexibilityEntropy>=.8&&distinctSequences>=3?'VERY_FLEXIBLE':flexibilityEntropy>=.55?'FLEXIBLE':flexibilityEntropy>=.3?'MODERATE':openings.winningFirstActionCount?'NARROW':'VERY_NARROW';
    const executionBand=overallWinRate>=.85?'VERY EASY':overallWinRate>=.65?'EASY':overallWinRate>=.4?'MODERATE':overallWinRate>=.2?'HARD':'VERY HARD';
    const summary=[];if(forgeRelevant&&contrasts.forgeVsGreedy>=thresholds.strongContrast)summary.push(`Forge-oriented agents outperform Greedy by ${Math.round(contrasts.forgeVsGreedy*100)} percentage points.`);if(contrasts.waitVsGreedy>=thresholds.strongContrast)summary.push(`WAIT-friendly agents outperform Greedy by ${Math.round(contrasts.waitVsGreedy*100)} percentage points.`);if(openings.traps[0])summary.push(`${actionName(openings.traps[0].action)} is a frequent trap: ${Math.round(openings.traps[0].attemptShare*100)}% chosen, ${Math.round(openings.traps[0].winRate*100)}% win rate.`);if(openings.forced)summary.push(`Successful attempts overwhelmingly begin with ${actionName(openings.topWinningOpening)}.`);if(openings.winningFirstActionCount>=2)summary.push(`${openings.winningFirstActionCount} observed openings lead to successful play.`);
    return{available:true,thresholds,oracle,metrics:{overallWinRate,balancedWinRate:balanced?.winRate??null,medianAgentWinRate:median(rates),minAgentWinRate:Math.min(...rates),maxAgentWinRate:Math.max(...rates),winRateSpread:Math.max(...rates)-Math.min(...rates),successfulArchetypeCount,failedArchetypeCount:ensemble.length-successfulArchetypeCount,averagePaidMovesOnWin:moveOnWin,averageActionCountOnWin:actionsOnWin,averageWaits:waits,oracleMoveGap,oracleAgreementRate,firstActionEntropy:openings.firstActionEntropy,winningFirstActionCount:openings.winningFirstActionCount,distinctSuccessfulSequenceCount:distinctSequences,mostCommonWinningSequenceShare:commonSequenceShare},difficulty,strategicSignals:{strategySeparation:maxContrast,openingTrapStrength:openings.traps[0]?openings.traps[0].attemptShare*(1-openings.traps[0].winRate):0,solutionNarrowness:clamp(1-flexibilityEntropy),agentDisagreement:clamp(Math.max(...rates)-Math.min(...rates)),oracleHumanGap:difficulty.optimality,timingDependence:difficulty.timing,forgeDependence:difficulty.forge,greedyPunishment:clamp(Math.max(contrasts.balancedVsGreedy||0,contrasts.balancedVsMaxYield||0))},agentContrasts:contrasts,openingAnalysis:openings,solutionFlexibility:{band:flexibility,successfulFirstActionEntropy:flexibilityEntropy,observedWinningFirstActions:openings.winningFirstActionCount,distinctSuccessfulSequenceCount:distinctSequences,mostCommonWinningSequenceShare:commonSequenceShare,oracleOpeningAgreement:oracleAgreementRate},tags:[...new Set(tags)],summary,warnings:oracle?.status&&oracle.status!=='SOLVED'?[`Oracle status: ${oracle.status}`]:[]};
  }
  function runAnalysis(level,options={}){if(options.oracle||options.ensemble){return analyzeFromResults(level,{oracle:options.oracle||root.SootSeedLevelLabSolver.solveLevel(level,options.oracleOptions),ensemble:options.ensemble||root.SootSeedLevelLabAgents.runEnsemble(level,options.ensembleOptions)});}const key=JSON.stringify({level,oracleOptions:options.oracleOptions||{},ensembleOptions:options.ensembleOptions||{}});if(resultCache.has(key))return resultCache.get(key);const result=analyzeFromResults(level,{oracle:root.SootSeedLevelLabSolver.solveLevel(level,options.oracleOptions),ensemble:root.SootSeedLevelLabAgents.runEnsemble(level,options.ensembleOptions)});resultCache.set(key,result);return result;}
  root.SootSeedLevelLabAnalysis={thresholds,analyzeFromResults,runAnalysis,openingAnalysis,clearCache:()=>resultCache.clear()};
})(globalThis);
