(function(root){
  const oraclePresets={fast:{maxExploredStates:3000,maxGeneratedStates:12000,maxActionDepth:20},normal:{maxExploredStates:7000,maxGeneratedStates:30000,maxActionDepth:28},deep:{maxExploredStates:25000,maxGeneratedStates:100000,maxActionDepth:36}};
  const ensemblePresets={quick:{attempts:5},normal:{attempts:10},deep:{attempts:20}};
  const clone=root.SootSeedLevelLabCandidates.clone;
  const initialCounters=requested=>({requested,generationAttempts:0,rejectedMutation:0,invalid:0,duplicates:0,oracleUnsolvable:0,oracleUnresolved:0,solved:0,fullyEvaluated:0,cancelled:false,retryBudgetExhausted:false});
  const batchId=(seed,seedValue,depth,count)=>`${seed}-S${seedValue}-M${depth}-N${count}`.replace(/[^a-zA-Z0-9-]/g,'-');
  function recordMutation(stats,id,field){const entry=stats[id]||{generated:0,solved:0};entry[field]++;stats[id]=entry;}
  function makeCandidate(seedCandidate,index,rng,depth,config,batch){let level=clone(seedCandidate.level),context={},history=[],ids=[];for(let step=0;step<depth;step++){const result=root.SootSeedLevelLabMutations.mutateLevel(level,rng,config,context);if(!result)return null;level=result.level;history.push(result.history);ids.push(result.mutation.id);context={...context,...(result.contextPatch||{})};}const fingerprint=root.SootSeedLevelLabMutations.fingerprint(level);return root.SootSeedLevelLabCandidates.createCandidate(seedCandidate.seedLevelId,level,{id:`${batch.id}-C${String(index).padStart(3,'0')}-${fingerprint.length.toString(36)}`,generation:0,parentId:seedCandidate.id,mutations:history,metadata:{batchId:batch.id,rngSeed:batch.rngSeed,mutationIds:ids,mutationDepth:depth,fingerprint}});}
  function evaluate(candidate,options){const validation=root.SootSeedLevelLabValidation.validate(candidate.level);if(!validation.ok)return{candidate:{...candidate,evaluation:{...root.SootSeedLevelLabTypes.emptyEvaluation(),status:'invalid',structural:validation.structural,staticSanity:validation.staticSanity}},stage:'invalid'};const oracle=root.SootSeedLevelLabSolver.solveLevel(candidate.level,options.oracleOptions);let status='solved',agents=null,analysis=null;if(oracle.status==='UNSOLVABLE')status='unsolvable';else if(oracle.status!=='SOLVED')status='unresolved';else{agents=root.SootSeedLevelLabAgents.runEnsemble(candidate.level,{...options.ensembleOptions,seed:`${options.ensembleSeed}:${candidate.id}`});analysis=root.SootSeedLevelLabAnalysis.analyzeFromResults(candidate.level,{oracle,ensemble:agents});}return{candidate:{...candidate,evaluation:{status,structural:validation.structural,staticSanity:validation.staticSanity,oracle,agents,analysis}},stage:status};}
  function generateBatchSync(options={}){const seedCandidate=options.seedCandidate||root.SootSeedLevelLabCandidates.createCandidate(options.seedLevelId||options.seedLevel?.id||'custom-seed',options.seedLevel||options.level,{id:`candidate-${options.seedLevelId||'custom'}-seed`});if(!seedCandidate?.level)throw new Error('A seed candidate or seed level is required.');const count=Number(options.count||50),depth=Math.max(1,Math.min(4,Number(options.mutationDepth||options.mutationConfig?.depth||2))),rngSeed=String(options.rngSeed??'12345'),rng=root.SootSeedLevelLabRng.createSeededRng(rngSeed),id=options.batchId||batchId(seedCandidate.seedLevelId,rngSeed,depth,count),maxAttempts=Number(options.maxAttempts||count*5),config={...root.SootSeedLevelLabMutations.defaultMutationConfig,...(options.mutationConfig||{})},oracleOptions={...oraclePresets[options.oraclePreset||'normal'],...(options.oracleOptions||{})},ensembleOptions={...ensemblePresets[options.ensemblePreset||'quick'],...(options.ensembleOptions||{})},batch={id,rngSeed,seedLevelId:seedCandidate.seedLevelId,seedFingerprint:root.SootSeedLevelLabMutations.fingerprint(seedCandidate.level),config:{count,depth,oraclePreset:options.oraclePreset||'normal',ensemblePreset:options.ensemblePreset||'quick'},counters:initialCounters(count),mutationStats:{},candidates:[],allCandidates:[]},fingerprints=new Set([batch.seedFingerprint]);
    while(batch.candidates.length<count&&batch.counters.generationAttempts<maxAttempts){if(options.cancelToken?.cancelled){batch.counters.cancelled=true;break;}batch.counters.generationAttempts++;const candidate=makeCandidate(seedCandidate,batch.counters.generationAttempts,rng,depth,config,batch);if(!candidate){batch.counters.rejectedMutation++;continue;}for(const mutationId of candidate.metadata.mutationIds)recordMutation(batch.mutationStats,mutationId,'generated');const validation=root.SootSeedLevelLabValidation.validate(candidate.level);if(!validation.ok){batch.counters.invalid++;if(options.retainFailed)batch.allCandidates.push({...candidate,evaluation:{status:'invalid',structural:validation.structural,staticSanity:validation.staticSanity}});continue;}const fingerprint=candidate.metadata.fingerprint;if(fingerprints.has(fingerprint)){batch.counters.duplicates++;continue;}fingerprints.add(fingerprint);const evaluated=evaluate(candidate,{oracleOptions,ensembleOptions,ensembleSeed:options.ensembleSeed??rngSeed});batch.allCandidates.push(evaluated.candidate);if(evaluated.stage==='unsolvable'){batch.counters.oracleUnsolvable++;if(options.retainFailed)batch.candidates.push(evaluated.candidate);continue;}if(evaluated.stage==='unresolved'){batch.counters.oracleUnresolved++;if(options.retainFailed)batch.candidates.push(evaluated.candidate);continue;}if(evaluated.stage==='invalid'){batch.counters.invalid++;if(options.retainFailed)batch.candidates.push(evaluated.candidate);continue;}batch.counters.solved++;batch.counters.fullyEvaluated++;for(const mutationId of candidate.metadata.mutationIds)recordMutation(batch.mutationStats,mutationId,'solved');batch.candidates.push(evaluated.candidate);options.onProgress?.(batch);}
    if(batch.candidates.length<count&&!batch.counters.cancelled)batch.counters.retryBudgetExhausted=true;return batch;
  }
  async function generateCandidateBatch(options={}){return generateBatchSync(options);}
  function generateOne(seedCandidate,mutationId,rng){return root.SootSeedLevelLabMutations.applyMutation(seedCandidate,mutationId,rng);}
  root.SootSeedLevelLabGeneration={oraclePresets,ensemblePresets,batchId,generateOne,generateBatchSync,generateCandidateBatch,evaluate};
})(globalThis);
