(function(root){
  const clone=root.SootSeedLevelLabCandidates.clone;
  const cardinal=[[1,0],[-1,0],[0,1],[0,-1]],nearby=[...cardinal,[1,1],[1,-1],[-1,1],[-1,-1]];
  const resourceNames={wood:'Wood',wheat:'Wheat',charcoal:'Charcoal',iron:'Iron'};
  const defaultMutationConfig={depth:2,weights:{'move-tree-local':8,'add-tree-edge':5,'remove-tree-edge':4,'move-wheat-local':8,'add-wheat-edge':5,'remove-wheat-edge':4,'move-ore-edge':4,'add-ore-edge':2,'remove-ore-edge':2,'adjust-requirement':8,'adjust-move-limit':6,'scheduled-fire-earlier':4,'scheduled-fire-later':4,'move-ignition-local':3}};
  const key=(r,c)=>`${r},${c}`;
  const inBounds=(level,r,c)=>r>=0&&c>=0&&r<level.map.length&&c<(level.map[0]?.length||0);
  const cell=(level,r,c)=>inBounds(level,r,c)?level.map[r][c]:null;
  const positions=(level,symbol)=>{const out=[];level.map.forEach((row,r)=>{for(let c=0;c<row.length;c++)if(row[c]===symbol)out.push({r,c});});return out;};
  const replace=(level,r,c,value)=>{const row=level.map[r];level.map[r]=row.slice(0,c)+value+row.slice(c+1);};
  const shuffle=(items,rng)=>{const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=rng.int(i+1);[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;};
  const choose=(items,rng)=>items.length?items[rng.int(items.length)]:null;
  // Resources are only introduced on plain ground; fire, houses, ore and void are never overwritten.
  function emptyNeighbours(level,source,deltas,rng){return shuffle(deltas,rng).map(([dr,dc])=>({r:source.r+dr,c:source.c+dc})).filter(point=>cell(level,point.r,point.c)==='.');}
  function edgeGround(level,symbol,rng){for(const anchor of shuffle(positions(level,symbol),rng)){const target=choose(emptyNeighbours(level,anchor,cardinal,rng),rng);if(target)return target;}return null;}
  function moveResource(symbol,label){return{id:`move-${label.toLowerCase()}-local`,name:`Move ${label} locally`,description:`Moves one ${label} one nearby tile without overwriting another object.`,weight:8,riskCategory:'low',affectedArea:'local resource',canApply(level){return positions(level,symbol).some(source=>nearby.some(([dr,dc])=>cell(level,source.r+dr,source.c+dc)==='.'));},apply(level,rng){const next=clone(level);for(const source of shuffle(positions(next,symbol),rng)){const target=choose(emptyNeighbours(next,source,nearby,rng),rng);if(!target)continue;replace(next,source.r,source.c,'.');replace(next,target.r,target.c,symbol);return{level:next,history:`Moved ${label} (${source.r+1},${source.c+1}) → (${target.r+1},${target.c+1})`,targets:[key(source.r,source.c),key(target.r,target.c)]};}return null;}};}
  function addResource(symbol,label){return{id:`add-${label.toLowerCase()}-edge`,name:`Add ${label} at edge`,description:`Grows a ${label} formation by one orthogonally adjacent tile.`,weight:5,riskCategory:'medium',affectedArea:'local resource',canApply(level){return !!edgeGround(level,symbol,{int:max=>0});},apply(level,rng){const next=clone(level),target=edgeGround(next,symbol,rng);if(!target)return null;replace(next,target.r,target.c,symbol);return{level:next,history:`Added ${label} at (${target.r+1},${target.c+1})`,targets:[key(target.r,target.c)]};}};}
  function removeResource(symbol,label){return{id:`remove-${label.toLowerCase()}-edge`,name:`Remove ${label} at edge`,description:`Removes one ${label} from an existing formation.`,weight:4,riskCategory:'medium',affectedArea:'local resource',canApply(level){return positions(level,symbol).length>0;},apply(level,rng){const next=clone(level),source=choose(positions(next,symbol),rng);if(!source)return null;replace(next,source.r,source.c,'.');return{level:next,history:`Removed ${label} at (${source.r+1},${source.c+1})`,targets:[key(source.r,source.c)]};}};}
  const requirementMutation={id:'adjust-requirement',name:'Adjust requirement',description:'Changes one resource requirement by one, staying non-negative.',weight:8,riskCategory:'medium',affectedArea:'requirements',canApply(level,context={}){return Object.keys(level.req||{}).some(kind=>resourceNames[kind]&&!(context.requirementChanges?.[kind]&&Math.abs(context.requirementChanges[kind])>=1));},apply(level,rng,context={}){const next=clone(level),choices=Object.keys(next.req||{}).filter(kind=>resourceNames[kind]&&!(context.requirementChanges?.[kind]&&Math.abs(context.requirementChanges[kind])>=1)),kind=choose(choices,rng);if(!kind)return null;const before=next.req[kind],direction=choose(before>0?[-1,1]:[1],rng),after=before+direction;next.req[kind]=after;return{level:next,history:`${resourceNames[kind]} requirement ${before} → ${after}`,contextPatch:{requirementChanges:{...(context.requirementChanges||{}),[kind]:(context.requirementChanges?.[kind]||0)+direction}},targets:[`requirement:${kind}`]};}};
  const moveLimitMutation={id:'adjust-move-limit',name:'Adjust move limit',description:'Adds or removes one paid move while retaining a legal positive limit.',weight:6,riskCategory:'medium',affectedArea:'move limit',canApply(level,context={}){return !context.moveLimitChanged;},apply(level,rng){const next=clone(level),before=next.moves,direction=before<=1?1:choose([-1,1],rng),after=before+direction;if(after<1)return null;next.moves=after;return{level:next,history:`Move limit ${before} → ${after}`,contextPatch:{moveLimitChanged:true},targets:['moves']};}};
  function fireTiming(direction,label){return{id:`scheduled-fire-${label}`,name:`Scheduled fire ${label}`,description:`Moves one scheduled fire ${label} by one world step.`,weight:4,riskCategory:'medium',affectedArea:'scheduled fire',canApply(level,context={}){return(level.fires||[]).some((fire,index)=>fire.after+direction>=1&&!context.fireTimingChanged?.[index]);},apply(level,rng,context={}){const next=clone(level),valid=next.fires.map((fire,index)=>({fire,index})).filter(({fire,index})=>fire.after+direction>=1&&!context.fireTimingChanged?.[index]),picked=choose(valid,rng);if(!picked)return null;const before=picked.fire.after,after=before+direction;next.fires[picked.index]={...picked.fire,after};return{level:next,history:`Scheduled Fire at (${picked.fire.r+1},${picked.fire.c+1}) step ${before} → ${after}`,contextPatch:{fireTimingChanged:{...(context.fireTimingChanged||{}),[picked.index]:true}},targets:[`fire:${picked.index}`]};}};}
  const moveIgnition={id:'move-ignition-local',name:'Move ignition locally',description:'Moves one scheduled ignition to a nearby valid board tile.',weight:3,riskCategory:'high',affectedArea:'fire topology',canApply(level,context={}){return(level.fires||[]).some((fire,index)=>!context.ignitionMoved?.[index]&&nearby.some(([dr,dc])=>{const value=cell(level,fire.r+dr,fire.c+dc);return value!==null&&value!=='#'&&value!=='H';}));},apply(level,rng,context={}){const next=clone(level),choices=next.fires.map((fire,index)=>({fire,index})).filter(({index})=>!context.ignitionMoved?.[index]);for(const picked of shuffle(choices,rng)){const target=shuffle(nearby,rng).map(([dr,dc])=>({r:picked.fire.r+dr,c:picked.fire.c+dc})).find(point=>inBounds(next,point.r,point.c)&&cell(next,point.r,point.c)!=='#'&&cell(next,point.r,point.c)!=='H');if(!target)continue;next.fires[picked.index]={...picked.fire,r:target.r,c:target.c};return{level:next,history:`Moved ignition (${picked.fire.r+1},${picked.fire.c+1}) → (${target.r+1},${target.c+1})`,contextPatch:{ignitionMoved:{...(context.ignitionMoved||{}),[picked.index]:true}},targets:[`fire:${picked.index}`,key(target.r,target.c)]};}return null;}};
  const registry=[moveResource('T','Tree'),addResource('T','Tree'),removeResource('T','Tree'),moveResource('W','Wheat'),addResource('W','Wheat'),removeResource('W','Wheat'),moveResource('O','Ore'),addResource('O','Ore'),removeResource('O','Ore'),requirementMutation,moveLimitMutation,fireTiming(-1,'earlier'),fireTiming(1,'later'),moveIgnition];
  function fingerprint(level){return JSON.stringify({map:[...(level.map||[])],moves:level.moves,req:Object.fromEntries(Object.keys(level.req||{}).sort().map(k=>[k,level.req[k]])),tools:[...(level.tools||[])].sort(),wind:level.wind||null,fires:[...(level.fires||[])].map(f=>({r:f.r,c:f.c,after:f.after})).sort((a,b)=>a.r-b.r||a.c-b.c||a.after-b.after)});}
  function applicable(level,rng,context={},config={}){const weights={...defaultMutationConfig.weights,...(config.weights||{})};return registry.filter(m=>(weights[m.id]??m.weight)>0&&m.canApply(level,context)).map(m=>({...m,weight:weights[m.id]??m.weight}));}
  function pickWeighted(items,rng){const total=items.reduce((sum,item)=>sum+item.weight,0);let value=rng.next()*total;for(const item of items){value-=item.weight;if(value<0)return item;}return items[items.length-1]||null;}
  function mutateLevel(level,rng,config={},context={}){const mutation=pickWeighted(applicable(level,rng,context,config),rng);if(!mutation)return null;const before=fingerprint(level),result=mutation.apply(level,rng,context);if(!result||fingerprint(result.level)===before)return null;return{...result,mutation};}
  function applyMutation(candidate,id,rng,context={}){const mutation=registry.find(item=>item.id===id);if(!mutation)throw new Error(`Unknown mutation: ${id}`);if(!mutation.canApply(candidate.level,context))throw new Error(`Mutation is not legal for ${candidate.id}.`);const before=fingerprint(candidate.level),result=mutation.apply(candidate.level,rng,context);if(!result||fingerprint(result.level)===before)throw new Error(`Mutation ${id} produced no level change.`);return root.SootSeedLevelLabTypes.candidate({...candidate,id:`${candidate.id}-${id}`,parentId:candidate.id,generation:candidate.generation+1,level:result.level,mutations:[...candidate.mutations,result.history],metadata:{...(candidate.metadata||{}),mutationIds:[...((candidate.metadata||{}).mutationIds||[]),id]},evaluation:root.SootSeedLevelLabTypes.emptyEvaluation()});}
  root.SootSeedLevelLabMutations={registry,defaultMutationConfig,fingerprint,applicable,pickWeighted,mutateLevel,applyMutation,inBounds};
})(globalThis);
