(function(root){
  const clamp=value=>Math.max(0,Math.min(1,Number.isFinite(value)?value:0));
  const archivePresets={
    general:{id:'general',name:'General',x:{id:'constraint',label:'Strategic constraint'},y:{id:'separation',label:'Strategy separation'}},
    timing:{id:'timing',name:'Timing',x:{id:'timing',label:'Timing dependence'},y:{id:'constraint',label:'Strategic constraint'}},
    forge:{id:'forge',name:'Forge',x:{id:'forge',label:'Forge dependence'},y:{id:'greedy',label:'Greedy punishment'}},
    openness:{id:'openness',name:'Openness',x:{id:'flexibility',label:'Solution flexibility'},y:{id:'execution',label:'Execution difficulty'}},
    disagreement:{id:'disagreement',name:'Disagreement',x:{id:'disagreement',label:'Agent disagreement'},y:{id:'oracleGap',label:'Oracle-human gap'}}
  };
  const defaultSearchConfig={generations:10,childrenPerGeneration:20,mutationDepthMin:1,mutationDepthMax:2,buckets:5,archivePreset:'general',oraclePreset:'normal',ensemblePreset:'quick',chunkSize:2};
  function signal(analysis,id){const s=analysis?.strategicSignals||{},d=analysis?.difficulty||{},f=analysis?.solutionFlexibility||{};return clamp({constraint:d.constraint,separation:s.strategySeparation,timing:d.timing,forge:d.forge,greedy:s.greedyPunishment,flexibility:1-(s.solutionNarrowness??(1-(f.successfulFirstActionEntropy??0))),execution:d.execution,disagreement:s.agentDisagreement,oracleGap:s.oracleHumanGap}[id]);}
  function vector(analysis){return['execution','constraint','timing','resourcePlanning','forge','fireAwareness'].map(key=>clamp(analysis?.difficulty?.[key])).concat(['strategySeparation','solutionNarrowness','agentDisagreement','oracleHumanGap'].map(key=>clamp(analysis?.strategicSignals?.[key])));}
  function cellFor(analysis,presetId='general',buckets=5){const preset=archivePresets[presetId]||archivePresets.general,x=signal(analysis,preset.x.id),y=signal(analysis,preset.y.id),bucket=value=>Math.min(buckets-1,Math.floor(clamp(value)*buckets));return{preset:preset.id,x,y,xBucket:bucket(x),yBucket:bucket(y),key:`${bucket(x)},${bucket(y)}`,buckets};}
  function structuralDistance(rootLevel,level){const rows=Math.max(rootLevel.map.length,level.map.length),cols=Math.max(rootLevel.map[0]?.length||0,level.map[0]?.length||0);let changed=0;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)if((rootLevel.map[r]||'')[c]!==((level.map[r]||'')[c]))changed++;const tilePart=changed/Math.max(1,rows*cols),reqKeys=new Set([...Object.keys(rootLevel.req||{}),...Object.keys(level.req||{})]);let reqDelta=0;for(const key of reqKeys)reqDelta+=Math.abs((rootLevel.req?.[key]||0)-(level.req?.[key]||0));const fireA=rootLevel.fires||[],fireB=level.fires||[];let fireDelta=Math.abs(fireA.length-fireB.length);for(let i=0;i<Math.min(fireA.length,fireB.length);i++)fireDelta+=Math.abs(fireA[i].r-fireB[i].r)+Math.abs(fireA[i].c-fireB[i].c)+Math.abs(fireA[i].after-fireB[i].after);return clamp(tilePart+(reqDelta+Math.abs(rootLevel.moves-level.moves)+fireDelta)/20);}
  function archiveQuality(candidate,rootLevel){const oracle=candidate.evaluation?.oracle,agents=candidate.evaluation?.agents||[],analysis=candidate.evaluation?.analysis||{},runs=agents.flatMap(agent=>agent.runs||[]),loopRate=runs.length?runs.filter(run=>['LOOP_DETECTED','ACTION_LIMIT_REACHED','WORLD_STEP_LIMIT_REACHED'].includes(run.reason)).length/runs.length:1,components={oracleSolved:oracle?.status==='SOLVED'?0.35:0,ensembleEvidence:agents.length?0.2:0,behaviourExpression:Math.min(.2,Math.max(analysis?.strategicSignals?.strategySeparation||0,analysis?.difficulty?.timing||0,analysis?.difficulty?.forge||0)*.2),solutionLength:oracle?.paidMoves>0?0.15:0,lowLoopRate:(1-loopRate)*.15,mutationRestraint:(1-structuralDistance(rootLevel,candidate.level))*.1};const score=Object.values(components).reduce((sum,value)=>sum+value,0);return{score,components,loopRate,distanceFromRoot:structuralDistance(rootLevel,candidate.level)};}
  function novelty(analysis,entries){const current=vector(analysis);if(!entries.length)return 1;return Math.min(...entries.map(entry=>Math.sqrt(current.reduce((sum,value,index)=>sum+(value-vector(entry.candidate.evaluation.analysis)[index])**2,0)/current.length)));}
  function createArchive(rootLevel,config={}){const presetId=config.archivePreset||'general',buckets=config.buckets||5,cells=new Map();return{presetId,buckets,cells,rootLevel,history:[],replacements:0,newCells:0,insert(candidate,generation){const cell=cellFor(candidate.evaluation.analysis,presetId,buckets),quality=archiveQuality(candidate,rootLevel),existing=cells.get(cell.key),entry={candidate,cell,quality,novelty:novelty(candidate.evaluation.analysis,[...cells.values()]),firstDiscovered:generation,replacementGenerations:[]};if(!existing){cells.set(cell.key,entry);this.newCells++;return{inserted:true,replaced:false,reason:'Cell was previously empty.',entry};}if(quality.score>existing.quality.score){entry.firstDiscovered=existing.firstDiscovered;entry.replacementGenerations=[...existing.replacementGenerations,generation];cells.set(cell.key,entry);this.replacements++;return{inserted:true,replaced:true,reason:`archiveQuality ${existing.quality.score.toFixed(2)} → ${quality.score.toFixed(2)}.`,entry,previous:existing};}return{inserted:false,replaced:false,reason:`Existing elite has archiveQuality ${existing.quality.score.toFixed(2)}.`,entry:existing};},coverage(){return cells.size/(buckets*buckets);},entries(){return[...cells.values()].sort((a,b)=>a.cell.yBucket-b.cell.yBucket||a.cell.xBucket-b.cell.xBucket);}};}
  function selectParent(search){const entries=search.archive.entries();if(!entries.length)return search.seedCandidate;const entry=entries[search.rng.int(entries.length)];search.metrics.parentSelection[entry.cell.key]=(search.metrics.parentSelection[entry.cell.key]||0)+1;return entry.candidate;}
  function makeChild(search,parent,generation,index){const rng=search.rng,depth=search.config.mutationDepthMin+rng.int(search.config.mutationDepthMax-search.config.mutationDepthMin+1);let level=root.SootSeedLevelLabCandidates.clone(parent.level),context=JSON.parse(JSON.stringify(parent.metadata?.mutationContext||{})),history=[],ids=[];for(let i=0;i<depth;i++){const mutation=root.SootSeedLevelLabMutations.mutateLevel(level,rng,{},context);if(!mutation)return null;level=mutation.level;history.push(mutation.history);ids.push(mutation.mutation.id);context={...context,...(mutation.contextPatch||{})};}const fingerprint=root.SootSeedLevelLabMutations.fingerprint(level);return root.SootSeedLevelLabCandidates.createCandidate(search.seedCandidate.seedLevelId,level,{id:`${search.id}-G${String(generation).padStart(2,'0')}-C${String(index).padStart(3,'0')}`,generation,parentId:parent.id,mutations:[...(parent.mutations||[]),...history],metadata:{batchId:search.id,rngSeed:search.seed,mutationIds:[...((parent.metadata||{}).mutationIds||[]),...ids],mutationDepth:depth,fingerprint,rootSeedId:search.seedCandidate.id,parentMutationHistory:history,mutationContext:context}});}
  function updateMetrics(search){search.metrics.archiveCoverage=search.archive.coverage();search.metrics.archiveOccupied=search.archive.cells.size;search.metrics.tagDistribution={};for(const entry of search.archive.entries())for(const tag of entry.candidate.evaluation.analysis?.tags||[])search.metrics.tagDistribution[tag]=(search.metrics.tagDistribution[tag]||0)+1;search.metrics.deepestLineage=Math.max(0,...search.candidates.map(candidate=>candidate.generation||0));}
  function evaluateChild(search,child){const fingerprint=child.metadata.fingerprint;if(search.seenFingerprints.has(fingerprint)){search.metrics.duplicates++;return null;}search.seenFingerprints.add(fingerprint);search.metrics.unique++;const evaluated=root.SootSeedLevelLabGeneration.evaluate(child,{oracleOptions:{...root.SootSeedLevelLabGeneration.oraclePresets[search.config.oraclePreset]},ensembleOptions:{...root.SootSeedLevelLabGeneration.ensemblePresets[search.config.ensemblePreset]},ensembleSeed:search.seed});const candidate=evaluated.candidate;search.candidates.push(candidate);if(evaluated.stage==='invalid'){search.metrics.invalid++;return candidate;}if(evaluated.stage==='unsolvable'){search.metrics.oracleUnsolvable++;return candidate;}if(evaluated.stage==='unresolved'){search.metrics.oracleUnresolved++;return candidate;}search.metrics.oracleSolved++;search.metrics.fullyEvaluated++;for(const id of child.metadata.mutationIds.slice(-child.metadata.mutationDepth))search.metrics.mutationSurvival[id]=search.metrics.mutationSurvival[id]||{generated:0,solved:0};for(const id of child.metadata.mutationIds.slice(-child.metadata.mutationDepth))search.metrics.mutationSurvival[id].solved++;candidate.metadata.archive=search.archive.insert(candidate,candidate.generation);return candidate;}
  function createSearch(options={}){const seedCandidate=options.seedCandidate||root.SootSeedLevelLabCandidates.createCandidate(options.seedLevelId||'seed',options.seedLevel||options.level,{id:`qd-${options.seedLevelId||'seed'}-root`});if(!seedCandidate?.level)throw new Error('QD search needs a seed candidate or level.');const config={...defaultSearchConfig,...options,mutationDepthMin:Math.max(1,options.mutationDepthMin??1),mutationDepthMax:Math.max(options.mutationDepthMin??1,options.mutationDepthMax??2)},seed=String(options.searchSeed??options.rngSeed??'12345'),id=options.id||`QD-${seedCandidate.seedLevelId}-S${seed}-G${config.generations}-C${config.childrenPerGeneration}`,archive=createArchive(seedCandidate.level,config),search={id,seed,config,seedCandidate,archive,rng:root.SootSeedLevelLabRng.createSeededRng(seed),seenFingerprints:new Set([root.SootSeedLevelLabMutations.fingerprint(seedCandidate.level)]),candidates:[],cancelToken:options.cancelToken||{cancelled:false},status:'ready',metrics:{attempted:0,unique:0,duplicates:0,invalid:0,oracleUnsolvable:0,oracleUnresolved:0,oracleSolved:0,fullyEvaluated:0,archiveCoverage:0,archiveOccupied:0,parentSelection:{},mutationSurvival:{},coverageHistory:[],deepestLineage:0},startedAt:null,elapsedMs:0};const seedEval=root.SootSeedLevelLabGeneration.evaluate(seedCandidate,{oracleOptions:{...root.SootSeedLevelLabGeneration.oraclePresets[config.oraclePreset]},ensembleOptions:{...root.SootSeedLevelLabGeneration.ensemblePresets[config.ensemblePreset]},ensembleSeed:seed});search.candidates.push(seedEval.candidate);if(seedEval.stage==='solved'){seedEval.candidate.metadata={...(seedEval.candidate.metadata||{}),archive:archive.insert(seedEval.candidate,0)};search.metrics.oracleSolved++;search.metrics.fullyEvaluated++;}updateMetrics(search);search.metrics.coverageHistory.push({generation:0,occupied:search.metrics.archiveOccupied,coverage:search.metrics.archiveCoverage});return search;}
  const yieldToBrowser=()=>new Promise(resolve=>setTimeout(resolve,0));
  async function runSearch(search,callbacks={}){search.status='running';search.startedAt=Date.now();for(let generation=1;generation<=search.config.generations;generation++){let newCellsBefore=search.archive.newCells,replacementsBefore=search.archive.replacements;for(let childIndex=1;childIndex<=search.config.childrenPerGeneration;childIndex++){if(search.cancelToken.cancelled){search.status='cancelled';updateMetrics(search);search.elapsedMs=Date.now()-search.startedAt;callbacks.onProgress?.(search,{generation,childIndex});return search;}search.metrics.attempted++;const parent=selectParent(search),child=makeChild(search,parent,generation,childIndex);if(!child){search.metrics.invalid++;continue;}for(const id of child.metadata.mutationIds.slice(-child.metadata.mutationDepth)){const stat=search.metrics.mutationSurvival[id]||{generated:0,solved:0};stat.generated++;search.metrics.mutationSurvival[id]=stat;}const evaluated=evaluateChild(search,child);callbacks.onCandidate?.(evaluated,search);if(childIndex%search.config.chunkSize===0){updateMetrics(search);callbacks.onProgress?.(search,{generation,childIndex,newCells:search.archive.newCells-newCellsBefore,replacements:search.archive.replacements-replacementsBefore});await yieldToBrowser();}}
      updateMetrics(search);search.metrics.coverageHistory.push({generation,occupied:search.metrics.archiveOccupied,coverage:search.metrics.archiveCoverage,newCells:search.archive.newCells-newCellsBefore,replacements:search.archive.replacements-replacementsBefore});callbacks.onProgress?.(search,{generation,childIndex:search.config.childrenPerGeneration,newCells:search.archive.newCells-newCellsBefore,replacements:search.archive.replacements-replacementsBefore});}
    search.status='completed';search.elapsedMs=Date.now()-search.startedAt;return search;
  }
  function lineage(search,candidateId){const byId=new Map(search.candidates.map(candidate=>[candidate.id,candidate]));const out=[];let current=byId.get(candidateId);while(current){out.unshift(current);current=byId.get(current.parentId);}return out;}
  function project(search,presetId){const archive=createArchive(search.seedCandidate.level,{archivePreset:presetId,buckets:search.config.buckets});for(const candidate of search.candidates.filter(item=>item.evaluation?.status==='solved'))archive.insert(candidate,candidate.generation);return archive;}
  root.SootSeedLevelLabQD={archivePresets,defaultSearchConfig,signal,vector,cellFor,structuralDistance,archiveQuality,createArchive,createSearch,runSearch,lineage,project};
})(globalThis);
