(function(root){
const sim=root.SootSeedSimulation;
function stateHash(s){return JSON.stringify({c:s.cells.map(r=>r.map(x=>[x.terrain,x.object,x.state,+!!x.wet,+!!x.charcoalPending,x.ignition?[x.ignition.after,+!!x.ignition.fired]:null])),m:s.moves,a:s.actions,r:[s.res.wood,s.res.charcoal,s.res.wheat,s.res.iron],h:+!!s.houseLost,ht:s.housesTotal});}
const actionId=a=>a.tool==='wait'?'WAIT':`${a.tool.toUpperCase()}@(${a.r+1},${a.c+1})`;
const formatAction=a=>a.tool==='wait'?'WAIT':`${a.tool.toUpperCase()} — ${a.tool==='forge'?'placement':'region'} at (${a.r+1},${a.c+1})`;
function canonicalActions(level,state){const seen=new Set(),out=[];for(const a of sim.getLegalActions(level,state)){let k=actionId(a);if(a.tool==='sickle'||a.tool==='woodcutter')k=`${a.tool}:${sim.region(state,a.r,a.c,a.tool==='sickle'?'wheat':'tree').map(p=>p.join(',')).sort().join('|')}`;if(!seen.has(k)){seen.add(k);out.push(a);}}return out.sort((a,b)=>actionId(a).localeCompare(actionId(b)));}
function solveLevel(level,o={}){const lim={maxExploredStates:o.maxExploredStates??25000,maxGeneratedStates:o.maxGeneratedStates??100000,maxActionDepth:o.maxActionDepth??32},validation=root.SootSeedLevelLabValidation?.validate(level);if(validation&&!validation.ok)return{status:'INVALID_LEVEL',solvable:false,solutionActions:[],terminationReason:'validation failed',validation};let generated=1,explored=0,duplicates=0,maxFrontier=1;const start=sim.createInitialState(level),q=[{state:start,path:[],paid:0}],best=new Map([[stateHash(start),[0,0]]]),finish=(status,node,why,extra={})=>({status,solvable:status==='SOLVED',solutionActions:status==='SOLVED'?node.path:[],solutionText:status==='SOLVED'?node.path.map(formatAction):[],paidMoves:status==='SOLVED'?node.paid:null,worldSteps:status==='SOLVED'?node.state.actions:null,actionCount:status==='SOLVED'?node.path.length:null,exploredStates:explored,generatedStates:generated,duplicateStatesSkipped:duplicates,maximumFrontier:maxFrontier,searchDepth:node?.path.length||0,terminationReason:why,...extra});
while(q.length){q.sort((a,b)=>a.paid-b.paid||a.path.length-b.path.length||stateHash(a.state).localeCompare(stateHash(b.state)));const n=q.shift();if(++explored>lim.maxExploredStates)return finish('SEARCH_LIMIT_REACHED',n,'max explored states');if(sim.getGameStatus(level,n.state).won){let replay=sim.createInitialState(level);try{for(const a of n.path)replay=sim.applyAction(level,replay,a).state;}catch(e){return finish('ERROR',n,'replay threw',{error:String(e)});}return sim.getGameStatus(level,replay).won?finish('SOLVED',n,'solution replay verified'):finish('ERROR',n,'replay did not win');}if(n.path.length>=lim.maxActionDepth)continue;for(const a of canonicalActions(level,n.state)){if(++generated>lim.maxGeneratedStates)return finish('SEARCH_LIMIT_REACHED',n,'max generated states');const next=sim.applyAction(level,n.state,a).state,paid=level.moves-next.moves,depth=n.path.length+1,h=stateHash(next),old=best.get(h);if(old&&(old[0]<paid||(old[0]===paid&&old[1]<=depth))){duplicates++;continue;}best.set(h,[paid,depth]);q.push({state:next,path:[...n.path,a],paid});maxFrontier=Math.max(maxFrontier,q.length);}}
return finish('UNSOLVABLE',{path:[],state:start,paid:0},'frontier exhausted');}
function createOracleResult(){return{status:'not-run',solvable:null,solutionActions:[],exploredStates:0,generatedStates:0,duplicateStatesSkipped:0};}
root.SootSeedLevelLabSolver={stateHash,actionId,formatAction,canonicalActions,solveLevel,createOracleResult};
})(globalThis);
