(function(root){
  const store=root.SootSeedLevelLabCandidateStore;
  let candidate=null;
  const byId=id=>document.querySelector(id);
  const safe=text=>String(text??'').replace(/[&<>]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[char]));
  function seeds(){return root.campaignEntries.filter(entry=>entry.level);}
  function loadSeed(){const entry=seeds().find(item=>item.id===byId('#levelLabSeed').value);candidate=root.SootSeedLevelLabCandidates.createCandidate(entry.id,entry.level,{id:`candidate-${entry.id}-seed`});store.add(candidate);render();}
  function mutate(){if(!candidate)return;const mutation=root.SootSeedLevelLabMutations.registry.find(item=>item.canApply(candidate.level));if(!mutation)return;candidate=root.SootSeedLevelLabGeneration.generateOne(candidate,mutation.id,root.SootSeedLevelLabRng.createSeededRng(candidate.id));store.add(candidate);render();}
  function validate(){if(!candidate)return;candidate=root.SootSeedLevelLabEvaluation.evaluateCandidate(candidate);store.add(candidate);render();}
  function smoke(){if(!candidate)return;const result=root.SootSeedLevelLabEvaluation.smokeSimulation(candidate);byId('#levelLabSmokeResult').textContent=`Smoke simulation: ${result.initialActions} legal opening actions · ${result.status.worldSteps} world steps · ${result.status.paidMovesUsed} paid moves.`;}
  function play(){if(!candidate)return;root.loadCustomLevel(root.SootSeedLevelLabCandidates.clone(candidate.level),'Level Lab candidate');}
  function render(){const host=byId('#levelLabInfo'),details=byId('#levelLabDetails');if(!candidate){host.textContent='Load a campaign level as an immutable seed.';details.innerHTML='';return;}const validation=candidate.evaluation?.status||'not run',rows=[['Candidate ID',candidate.id],['Seed',candidate.seedLevelId],['Generation',candidate.generation],['Board',`${candidate.level.map[0].length} × ${candidate.level.map.length}`],['Moves',candidate.level.moves],['Requirements',Object.entries(candidate.level.req).map(([kind,value])=>`${kind} ${value}`).join(' · ')],['Validation',validation]];host.innerHTML=rows.map(([label,value])=>`<dt>${safe(label)}</dt><dd>${safe(value)}</dd>`).join('');details.innerHTML=`<h3>Mutation history</h3><p>${candidate.mutations.length?candidate.mutations.map(safe).join('<br>'):'None — immutable campaign seed.'}</p><h3>Future systems</h3><p>Oracle · Agent results · Difficulty · Candidate browser · Generations</p>`;}
  function open(){byId('#levelLabSeed').innerHTML=seeds().map(entry=>`<option value="${safe(entry.id)}">${entry.number} · ${safe(entry.title)}</option>`).join('');root.showScreen('levelLabScreen');render();}
  function mount(){const screen=document.createElement('section');screen.id='levelLabScreen';screen.className='screen level-lab-screen';screen.setAttribute('aria-label','Level Lab developer tool');screen.innerHTML=`<main class="level-lab"><p class="eyebrow">Developer tool</p><h1>Level Lab</h1><p class="lab-copy">Candidates are cloned from campaign seeds and evaluated by the authoritative game simulation. Nothing here changes campaign progress.</p><label>Seed Level <select id="levelLabSeed"></select></label><div class="lab-actions"><button id="levelLabLoad" type="button">Load Seed</button><button id="levelLabMutate" type="button">Create Test Mutation</button><button id="levelLabValidate" type="button">Validate</button><button id="levelLabSmoke" type="button">Run Smoke Simulation</button></div><dl id="levelLabInfo" class="lab-info"></dl><div id="levelLabDetails" class="lab-details"></div><p id="levelLabSmokeResult" class="lab-smoke"></p><div class="lab-actions"><button id="levelLabPlay" type="button">Play Candidate</button><button id="levelLabBack" type="button">Back</button></div></main>`;
    document.body.append(screen);const style=document.createElement('style');style.textContent='.level-lab{max-width:680px;margin:0 auto;padding:32px 20px 56px;color:#373b32}.level-lab h1{margin:.1em 0}.level-lab label{display:grid;gap:6px;font-weight:700}.level-lab select,.level-lab button{font:inherit;padding:10px;border-radius:10px}.lab-actions{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.lab-actions button{border:1px solid #80745c;background:#f2ead6;color:#373b32}.lab-info{display:grid;grid-template-columns:max-content 1fr;gap:7px 14px;padding:16px;background:#f7f1e3;border-radius:12px}.lab-info dt{font-weight:700}.lab-info dd{margin:0}.lab-details{font-size:.92rem}.lab-copy,.lab-smoke{color:#676154}.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-size:.74rem}';document.head.append(style);
    byId('#levelLabLoad').onclick=loadSeed;byId('#levelLabMutate').onclick=mutate;byId('#levelLabValidate').onclick=validate;byId('#levelLabSmoke').onclick=smoke;byId('#levelLabPlay').onclick=play;byId('#levelLabBack').onclick=()=>root.showMenu();
    const controls=document.querySelector('.campaign-debug');if(controls){const button=document.createElement('button');button.type='button';button.textContent='Level Lab';button.onclick=open;controls.append(button);}
  }
  root.SootSeedLevelLabUI={mount,open};
})(globalThis);
